### ISSUE TITLE
Remove redundant entries?

### ISSUE THREAD

**Issue by baskerville** [gabomdq/SDL_GameControllerDB#102]
A few gamepads are already defined in *SDL 2.04*'s source (in `src/joystick/SDL_gamecontrollerdb.h`).

It might be worth writing a script that removes the relevant lines from the DB.

**Comment by CreamyCookie** [comment]
Please don't. Not everyone may use this with SDL2.

**Comment by gabomdq** [comment]
Redundancy is "by design" since you can overwrite SDL internal mappings with your own.
