### ISSUE TITLE
Mapping for Mad Catz Fightpad SFxT

### ISSUE THREAD

**Issue by terzag** [gabomdq/SDL_GameControllerDB#103]
As said in the title, here is the mapping I have for my Mad Catz Fightpad "Street Fighter x Tekken". I thought I had already reported it but I don't see it in the list.

03000000ad1b00002ef0000090040000,Mad Catz Fightpad SFxT,platform:Linux,a:b0,b:b1,y:b3,x:b2,start:b7,guide:b8,back:b6,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,lefttrigger:a2,righttrigger:a5

I assume it should be the same for all Mad Catz Fightpads and not the "Street Fighter x Tekken" editions specifically but just in case...

**Comment by gabomdq** [comment]
Merged, thanks!
