### ISSUE TITLE
Adding a controller mapping for Android + Some GUID-related note

### ISSUE THREAD

**Issue by NY00123** [gabomdq/SDL_GameControllerDB#104]
So I've noticed that there's no mapping for Android in this repository; SDL2's SDL_gamecontrollerdb.h header has an internal mapping for the NVIDIA Shield controller, but that's it.

In my case, it's a twin PSX/PS2 adapter with a duplicated GUID of 03000000100800000100000010010000 (for two possible controllers), as reported on Ubuntu 14.04. The GUID itself, as well as a compatible mapping, are already present in this repository (although SDL2's testjoystick reports the joystick name of "Twin USB Joystick" for each controller, rather than "Twin USB PS2 Adapter").

Using a (quite) recent revision of SDL2, I have a working mapping for Android, and I can post it.

However, I've noticed that the GUID is currently just a part of the joystick's name on Android. Instead, the function InputDevice.getDescriptor() can be used, but this requires API level 16 or later.

These are the descriptors which I got for the two controllers on an android-x86-5.1-rc1.iso VM (they don't share the same descriptor): c6cb90158061a88b1ec3d7ad69bb16a621eb897e, ab5fdd8d1a14fc069dc3d249ecd9f0dbc188bb87.

I got the same descriptors via an experimental naugatx8620160902.iso VM. Unfortunately I can't seem to use the controllers (including the USB/PS adapter) with a couple of actual Android-powered devices.

Given that API level 16 is required, I guess getDescriptor() won't be used soon, but it may still be better that I don't post the mapping itself for updating the db right now.

**Comment by gabomdq** [comment]
As I understand it, Android does its internal mapping before it gets to SDL, so controller mapping is not an issue in this platform...are you seeing something different? Like SDL not picking up it's a controller because it doesn't recognize the GUID? (In that case we should file a bug on SDL's bug tracker)

**Comment by NY00123** [comment]
If you're hinting that some standard Android-specific controller mapping can be used, then I'm afraid that's not the case.

On the one hand, according to SDL's mapping of the NVIDIA Shield controller for Android, key events with codes like KEYCODE_BUTTON_A and KEYCODE_BUTTON_SELECT (mapped to SDL joystick buttons in the range 0-10) are sent on button presses/releases. Apparently the same applies to other controllers, including XInput controllers.

On the other hand, with the above USB/PS adapter, KEYCODE_BUTTON_0..KEYCODE_BUTTON_11 (mapped to SDL joystick buttons 20..31) are sent. The lack of a standard layout for game controllers designed for PCs (ignoring XInput) also doesn't assist here, assuming such controllers are used with Android setups.

So I believe that per-controller mappings are still required.

I still think that I won't attach my mapping at the moment, in case the way the GUID is calculated on Android is changed.

**Comment by NY00123** [comment]
Since there apparently won't that more changed regarding SDL2's GUID calculations for a while, I've decided to attach my mapping for Android. This uses the older GUID format compatible with SDL versions <= 2.0.4. See PR #133 for the added mapping.

**Comment by p-groarke** [comment]
Hello, I have to do some research on the SDL Android mapping support before accepting/denying Android mappings. I will keep you posted on my findings. If there have been new developments and/or information about the Android platform, feel free to share.

**Comment by p-groarke** [comment]
Android is now supported in the db. I will accept android specific mappings from now on (same process as other platforms). Good day.
