### ISSUE TITLE
Add button labels to the DB

### ISSUE THREAD

**Issue by Ident** [gabomdq/SDL_GameControllerDB#120]
The buttons in the DB all map to XBOX360 style names. In order to display a representation of the physical button on the device in the UI, a symbol name would be required for each mapped button. E.g.: "square", "green", etc.

I am not sure how this could be added to the current txt file in a way it could not intefere with the way it is parsed.

Is this something that has been considered before and would it make sense to add this to this lib?

**Comment by gabomdq** [comment]
This (and other extensions to the DB format) have been talked about in the SDL distribution list, so far no progress on it (that I know of).

**Comment by aaronfranke** [comment]
What is the status of this? https://github.com/gabomdq/SDL_GameControllerDB/tree/buttons

**Comment by p-groarke** [comment]
@aaronfranke Very dead ;)
