### ISSUE TITLE
Xinmo Dual Arcade left/down vs right/up issue

### ISSUE THREAD

**Issue by grgohr** [gabomdq/SDL_GameControllerDB#123]
anybody knows a proper txt for that controller ?
the 1P stick mixes up left/right and up/down as the same inputs, ignoring the directions, resulting in only left/bottom working

03000000c0160000e105000001010000,Xin-Mo Xin-Mo Dual Arcade,platform:Linux,b:b4,a:b3,x:b0,leftshoulder:b2,dpup:a1,dpdown:a1,start:b7,dpright:a0,rightshoulder:b5,guide:b9,y:b1,back:b6,dpleft:a0,

**Comment by D0NM** [comment]
Try this

`03000000c0160000e105000001010000,Xin-Mo Xin-Mo Dual Arcade,platform:Linux,b:b4,a:b3,x:b0,leftshoulder:b2,dpup:a0,dpdown:a0,start:b7,dpright:a1,rightshoulder:b5,guide:b9,y:b1,back:b6,dpleft:a1,`

**Comment by grgohr** [comment]
sorry, not sure to find the answer in those posts
that controller works fine anywhere with its mapping in retroarch or emulationstation, 
the issue comes with the new gamecontrollerdb.txt (PPSSPPSDL 1.3 specifically) : the above mapping does not work as it does not seem capable to manage negative values (1 positive value per axis is not enough)

a correct file should probably be something like the below which is not possible now :
03000000c0160000e105000001010000,Xin-Mo Xin-Mo Dual Arcade,platform:Linux,b:b4,a:b3,x:b0,leftshoulder:b2,dpup:a1,dpdown:a(-1),start:b7,dpright:a0,rightshoulder:b5,guide:b9,y:b1,back:b6,dpleft:a(-0),

**Comment by p-groarke** [comment]
Please open a PR with adequate mappings using the latest SDL version which supports the adequate modifiers.
