### ISSUE TITLE
Joystick UCOM UC-JS704C 

### ISSUE THREAD

**Issue by zaher** [gabomdq/SDL_GameControllerDB#125]
This mapping for my joystick UCOM UC-JS704C if you like to add to the list, i tested it in Windows8 and RetroPie on RaspBerryPie 1 Model B, using Love2D game

`45130010000000000000504944564944,Generic USB Joystick,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Windows,`

My computer and raspi too detected it as "Generic USB Joystick"

**Comment by p-groarke** [comment]
Available here : https://github.com/p-groarke/SDL_GameControllerDB

**Comment by p-groarke** [comment]
Closing: mapping was merged.
