### ISSUE TITLE
Issue with Microsoft X-Box One padv2

### ISSUE THREAD

**Issue by Nanoblender** [gabomdq/SDL_GameControllerDB#126]
The configuration for the Xbox one pad is wrong there are unnecessary assignation that create problems, here is a corrected version.
030000005e040000dd02000003020000,Microsoft X-Box One padv2,x:b2,a:b0,b:b1,y:b3,back:b6,guide:b8,start:b7,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,dpup:h0.1,leftshoulder:b4,lefttrigger:a2,rightshoulder:b5,righttrigger:a5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,platform:Linux,

**Comment by p-groarke** [comment]
The XBox mappings have been updated with the new inversion/range modifiers for SDL 2.0.6. I'm closing the issue as it probably fixes your problem. Please comment/reopen if it does not.
