### ISSUE TITLE
Duplicate mappings

### ISSUE THREAD

**Issue by CookiePLMonster** [gabomdq/SDL_GameControllerDB#128]
Two GUIDs, namely these:

`79000600000000000000504944564944,G-Shark GS-GP702,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,platform:Windows,`
`79000600000000000000504944564944,NGS Phantom,a:b2,b:b3,y:b1,x:b0,start:b9,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,platform:Windows,
`

and

`ff113133000000000000504944564944,SVEN X-PAD,platform:Windows,a:b2,b:b3,y:b1,x:b0,start:b5,back:b4,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b8,righttrigger:b9,`
`ff113133000000000000504944564944,Gembird JPD-DualForce,platform:Windows,a:b2,b:b3,x:b0,y:b1,start:b9,back:b8,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,leftstick:b10,rightstick:b11,
`

seem to be duplicated - ~is this a problem or does SDL2 resolve such by comparing the device name too?~

EDIT:
According to SDL2 docs:
```If a new mapping is loaded for an already known controller GUID, the later version will overwrite the one currently loaded.```

So seems like those duplicate mappings do nothing and one of them should be removed.

**Comment by D0NM** [comment]
It was me, who tested and added **JPD-DualForce.**
As you can seem both devices with the same GUID has different mappings.

**Comment by eddieray** [comment]
FWIW... here's the list of duplicates...
```
03000000341a00003608000000000000
03000000ffff00000000000000000000
030000006d04000016c2000000000000
030000006d04000019c2000000000000
03000000888800000803000000000000
030000004c0500006802000000000000
03000000250900000500000000000000
030000004c050000c405000000000000
030000004c050000cc09000000000000
030000004c050000a00b000000000000
030000006d04000018c2000000000000
03000000362800000100000000000000
03000000102800000900000000000000
03000000ff1100003133000000000000
03000000790000000600000000000000
```

**Comment by sandos** [comment]
I tried out my new "Data Frog" snes-style controller, and the GUID from SDL2 Gamepad Tool already exists, but the mapping is not correct, for this controller! Is there any way to handle these collisions other than removing one of the controllers?

**Comment by p-groarke** [comment]
Duplicate mappings have been removed. Furthermore, by converting to the unified GUIDs, old vs. new GUID duplicates have also been removed. Checks are also automatically run on new PRs to verify duplicates :)

**Comment by p-groarke** [comment]
@sandos Please open a specific issue for your problem.
