### ISSUE TITLE
README should explain how to name controllers

### ISSUE THREAD

**Issue by dreiss** [gabomdq/SDL_GameControllerDB#142]
I want to send a pull request for these controllers (https://smile.amazon.com/dp/B01MZAYQSV/), but there's one thing I don't understand: for the "name" field in the configuration line, should I write my own useful name (like "iNNEXT SNES Retro USB"), or use the name that came from controllermap (which is just "USB Gamepad ")?

If you let me know what's preferred, I can send a PR that updates the README as well.

**Comment by Enigma0** [comment]
I think the hardware ID is more important than the name. Descriptive but brief is probably best.

**Comment by p-groarke** [comment]
Yes the GUID is the most important value. The name is inconsequential.

**Comment by Enigma0** [comment]
@p-groarke I wouldn't say inconsequential. At minimum there ought to be some general formula for how they should be formated.

Something like [BRAND][MODEL][VERSION] - it's easier to confirm a name than the GUID at a glance.
