### ISSUE TITLE
cant add joystick through gamepadtool or steam big picture.[cannot detect device]

### ISSUE THREAD

**Issue by 012013014** [gabomdq/SDL_GameControllerDB#147]
hello there, sorry to disturb anyone, but i m really running out of idea.

i just bought a new old stock, a roydsstick.ex for ps3 to use in pc.
![sd4](https://user-images.githubusercontent.com/30760211/28999325-183d8bb4-7a75-11e7-83be-29a6b55d7159.jpg)

pc detected it as USB/PAD 
![sd](https://user-images.githubusercontent.com/30760211/28999290-b81fdddc-7a73-11e7-82cc-071d9deb42dc.png)

i can test it on the device and printers just fine.
![sd2](https://user-images.githubusercontent.com/30760211/28999299-fe44651c-7a73-11e7-8f63-3619ae980dd5.png)

but when i open steambig picture or gamepadtool[by General Arcade] it wont detect it .
![sd3](https://user-images.githubusercontent.com/30760211/28999312-547cb420-7a74-11e7-806f-f37a452b2d08.png)

i have no experience in programming or this sort of thing,been tinkering with it since 3-4 hour ago. i really hope some one can help me here.

most of the program or games i wanted to try wont detect it.

here is the device id for the joystick
HID\VID_1F4F&PID_0003&REV_0001

please help.....

**Comment by p-groarke** [comment]
This database is just for mappings. I recommend opening an issue on the SDL mailing list and/or forums to get help from the developers themselves.
