### ISSUE TITLE
inverting joystick axis in controllerdb.txt

### ISSUE THREAD

**Issue by tomismrkolj** [gabomdq/SDL_GameControllerDB#162]
Is there a way to invert joystick axis in controllerdb.txt?

I am tryng to map Microsoft Sidewinder Wheel and need to invert both pedal axis (accerelator and brakes)
Buttons work, steering is OK, accerlerator and brakes are mapped to right and left triggers.

Tomi

**Comment by flibitijibibo** [comment]
If you add '-' to the binding number it should invert it. '-a0' would, for example, flip axis 0.

**Comment by p-groarke** [comment]
Yes, it works with SDL 2.0.6 an onwards. There are some examples in the db.

**Comment by thfrwn** [comment]
I'm on SDL 2.0.5 (hopefully will eventually update, but for now stuck with this). On my system (yes, OpenBSD) the Y axes of an Xbox360 gamepad are wrong - they need to be inverted. I tried the tilde ~ to the binding number, but that didn't work. Any ideas if there's an equivalent for SDL 2.0.5?

**Comment by p-groarke** [comment]
There is no equivalent on SDL 2.0.5. The only option is to upgrade, sorry.

**Comment by thfrwn** [comment]
Thanks for letting me know. Prepared upgrade on our platform to 2.0.7 which was unproblematic and long overdue anyway...

**Comment by p-groarke** [comment]
:D

**Comment by p-groarke** [comment]
Note the notation for inversion is `a0~` and not `~a0`.

**Comment by thfrwn** [comment]
yes, I saw that in the file. Works. Thanks!

**Comment by p-groarke** [comment]
If you would like to submit an openbsd mapping, I would gladly add the platform and accept the mapping. You can use `platform: OpenBSD,` for the platform field. I've refactored the script so it is easy to add platforms :)

**Comment by thfrwn** [comment]
Thanks, that's good to know, but our implementation isn't there yet... The current workaround which only just enabled any form of gamecontroller API support on OpenBSD is to bypass where the check for haptic feedback fails and default to a XBox360 controller device. This part of the SDL2 code appears to be a failsafe for Linux platforms.

As a result, I can't customize the mapping with gamecontrollerdb.txt or SDL_GAMECONTROLLERCONFIG at the moment. Just tested this again. Will need to review the SDL2 code for a future update before we can make use of this.

(The `a0~` worked when compiling with a hardcoded mapping that includes this - this is how I know, in case you were wondering...)
