### ISSUE TITLE
Merge this into official SDL2

### ISSUE THREAD

**Issue by rsn8887** [gabomdq/SDL_GameControllerDB#165]
This should be merged into official SDL2 repo. Is there any reason why this is not done?

**Comment by p-groarke** [comment]
Yes, many. This db is "unofficial" in that we accept mappings that aren't tested by SDL developers. Obviously they cannot buy all the required controllers to officially test these mappings. The mappings provided in SDL itself have been tested and created by its developers.

Also see gabomdq's reasons here : https://github.com/gabomdq/SDL_GameControllerDB/issues/118

Good day.
