### ISSUE TITLE
Logitech Dual Action v2.00 not detected on macOS.

### ISSUE THREAD

**Issue by r-lind** [gabomdq/SDL_GameControllerDB#186]
Adding following line makes it work:
030000006d04000016c2000000020000,Logitech Dual Action,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b0,y:b3,platform:Mac OS X,

**Comment by p-groarke** [comment]
Hey, I hadn't seen the other mappings in the PR. I will re-open it with instructions. Sorry about that.
