### ISSUE TITLE
[Suggestion]  Improved mapping utility for GCDB submission

### ISSUE THREAD

**Issue by eddieray** [gabomdq/SDL_GameControllerDB#188]
The controllermap.c utility could use some improvement or a spin-off, to help make GCDB better.  I think controllermap.c is a contributed test program so I'd bet the SDL devs would be receptive to updates as they probably don't have time to focus on it very much.   I've been on the dev mailing list for a while and haven't seen much mention of this stuff.

We could create a new tool (maybe using controllermap.c as a starting point) for use here with GCDB that implements specific things that we want... like the new hints idea, checking for duplicate mappings, etc.  Currently, the tool people are directed to use is controllermap.c, so making a tool that is part of the GCDB effort will probably be useful for people who want to submit (and really, GCDB should be about allowing users who actually own the controllers to easily make submissions that make sense and "just work" with SDL games).

It's not crazy difficult, but it's also non-trivial to get the controllermap program working (download SDL source, find controlermap.c, figure out how to compile and run it) just so a person can submit a mapping for their whizzy cool controller.  It's tough for a non-techie to compile controllermap on all platforms.

Regarding submissions to the GCDB in general (from the controllermap.c utility), I would vote to scrutinize any new submissions with the notions about multiple mappings using the same input, diagonal inputs on the POV/DPAD controls and such.

**Comment by p-groarke** [comment]
As I've told you before, this repository has **no ties** with SDL. This **is not** the place to discuss controllermap. Furthermore, we already have a script that checks for duplicates and many other things.

Please contact the SDL project at libsdl.org if you have comments/questions/ideas for their software. If you make a new controller mapping software, I'll gladly add it to the readme.
