### ISSUE TITLE
PS4 controller on Android

### ISSUE THREAD

**Issue by Lumak** [gabomdq/SDL_GameControllerDB#189]
This is not an issue, but I'm not familiar with where I should post SDL related topics and apologize if this is an inconvenience to anyone.

I've tested a PS4 controller on my Android phone (API 16) recently and the GUID and the format is:
"576972656C65737320436F6E74726F6C,PS4 Controller,a:b1,b:b17,back:b16,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b7,leftshoulder:b3,leftstick:b4,lefttrigger:b9,leftx:a0,lefty:a1,rightshoulder:b18,rightstick:b6,righttrigger:a10,rightx:a2,righty:a5,start:b5,x:b0,y:b2,Android"

I'm not familiar with how Android generates controller GUID but would like to verify that it's consistent across various API levels.  If there's someone else out there with a PS4 controller and Android phone that can verify that it generates same GUID would be helpful.

**Comment by p-groarke** [comment]
The GUID looks consistent to other Android bindings. For example, the current Android PS4 GUID is "35643031303033326130316330353564".

SDL is using a different GUID format for mobile mappings. If you want more details on why, you can ask them at the SDL forums (discourse), I personally don't know why :)

**Comment by Lumak** [comment]
OK, thanks. I'll post it on the sdl discourse.
