### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by voznvlad** [gabomdq/SDL_GameControllerDB#199]
Hey guys!
I'm on OS X, trying to make PS4 Controller work with steam, tried putting your file into game folders of several games, modified steam config file (although it gets changed back when a game is launched) and it does not work. Any suggestions?

**Comment by p-groarke** [comment]
Hi, this database is not for steam itself. It is for game developers mostly. Many games aren't made with SDL, or don't use the file either.

You are better off contacting support for either steam or the games you play.
