### ISSUE TITLE
Suggestion: web page that lists supported controllers

### ISSUE THREAD

**Issue by Jjagg** [gabomdq/SDL_GameControllerDB#211]
It would be useful for developers to be able to point people to a simple web page that lists the controllers that their SDL game supports. Maybe this repo could add a web page (with GitHub Pages) that lists the supported controllers given a commit hash (and optionally SDL version) by parsing the database from the given commit.

**Comment by p-groarke** [comment]
You can use `sed` and a simple regex to extract the names from the db.

Feel free to make a website that does such a thing. It is out-of-scope for this project.

**Comment by Jjagg** [comment]
Thanks for the quick response!
