### ISSUE TITLE
What are the requirements for redistribution in other projects?

### ISSUE THREAD

**Issue by stevoisiak** [gabomdq/SDL_GameControllerDB#225]
I would like to use `gamecontrollerdb.txt` in an open source project that has been released under the GNU General Public License v3.0. The SDL_GameControllerDB [license file](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/LICENSE) says the project can be redistributed, but one restriction stuck out to me:

> 3. This notice may not be removed or altered from any source distribution.

Does this mean if I use any part of of SDL_GameControllerDB, the `LICENSE` file must also be included? If so, how would I distinguish SDL_GameControllerDB's license from the license of my own project?

**Comment by p-groarke** [comment]
First, I am not a lawyer and this is not legal advice.

You could use a subfolder with the db and license file inside, you can rename the license file so it is clear it is the gamecontrollerdb's license, or you could paste the license as a comment at the top of the db. It should simply be clear it is the database's license and the license should not be modified.
