### ISSUE TITLE
Any plans to push this upstream?

### ISSUE THREAD

**Issue by dscharrer** [gabomdq/SDL_GameControllerDB#23]
Are there any plans to get these mappings included in upstream [SDL_gamecontrollerdb.h](https://hg.libsdl.org/SDL/file/default/src/joystick/SDL_gamecontrollerdb.h)?

While I appreciate collecting this information in a perhaps more accessible location than the SDL hg repo, I feel that a lot more people would benefit if these defaults were shipped with SDL. Have you already contacted the SDL developers about this?

**Comment by JayFoxRox** [comment]
Right.. so why can't SDL just include this file as part of it's distribution? On Linux this could just end up in /usr/share or something. For windows this is generally more tricky (as no common location exists), but one could probably just attempt to load the file from the cwd or some ENV path?

It feels kind of dumb to include the database with every game / application.

**Comment by xDShot** [comment]
As stated before, these mappings should be verified.
