### ISSUE TITLE
PS3 Dualshock SixAxis incorrect mapping

### ISSUE THREAD

**Issue by Gamebuster19901** [gabomdq/SDL_GameControllerDB#238]
I noticed the mappings for my controller [PS3 Dualshock 3 Sixaxis](https://en.wikipedia.org/wiki/DualShock#DualShock_3) were incorrect, so I went to map them, however the mapping with the UUID it has already exists.

Should I make a PR to overwrite the old mapping?

The mapping should be
`
030000004c0500006802000000000000,PS3 Dualshock SixAxis,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b9,guide:b12,start:b8,leftstick:b10,rightstick:b11,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3~,righttrigger:a4~,`
`

But it is instead

`030000004c0500006802000000000000,PS3 Controller,a:b14,b:b13,back:b0,dpdown:b6,dpleft:b7,dpright:b5,dpup:b4,guide:b16,leftshoulder:b10,leftstick:b1,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b11,rightstick:b2,righttrigger:b9,rightx:a2,righty:a3,start:b3,x:b15,y:b12,platform:Windows,`

**Comment by Gamebuster19901** [comment]
Also, the drivers I'm using are the ones bundled with [PlaystationNow](https://www.playstation.com/en-us/explore/playstation-now/)

**Comment by p-groarke** [comment]
You can overwrite the old one, git will figure out what changed and what didn't.

**Comment by Gamebuster19901** [comment]
Apparently s an official SDL mapping,  so I'll report the issue there

**Comment by p-groarke** [comment]
Ah yes that may be the case. Be sure to mention your driver, that might be the difference. Thanks for trying to improve the db :)

**Comment by Gamebuster19901** [comment]
The official SDL mapping is already correct (see https://github.com/SDL-mirror/SDL/commit/09f1f2afaa4450de2b376b92a2ae922408e68dd2) but this mapping database doesn't appear to be updated for SDL 2.0.9.

**Comment by p-groarke** [comment]
We haven't updated to 2.0.9 yet. Will close this issue once I update our mappings and tests.

**Comment by p-groarke** [comment]
Our database has been update to the latest 2.0.9 upstream. There are *a lot* of new mappings in that release! :) Feel free to reopen if something went wrong.
