### ISSUE TITLE
About DualShock 3 triggers in one of mappings

### ISSUE THREAD

**Issue by CookiePLMonster** [gabomdq/SDL_GameControllerDB#247]
Hey,

while I realize this database is not supposed to overwrite stock SDL mappings, there is at least one which is plain wrong.

I'm talking about one of DS3 mappings, namely the one with GUID `050000004c0500006802000000800000`. In SDL (and thus in this database too) its triggers are defined as:
```
lefttrigger:b6,righttrigger:b7
```

however, mapping this specific controller in Steam Link app gives a better mapping, where triggers are axes:
```
lefttrigger:a2,righttrigger:a5
```

What should be done about this? Other DualShock 3 mappings have correctly mapped triggers, this one is an outlier and my pad just happens to use that mapping on Raspbian.

**Comment by p-groarke** [comment]
No worries, the best approach is to open a ticket on the SDL forums, or send them a pull request directly. 

Like you said, we don't change their mappings. When they fix theirs, we'll get the update. Cheers o/

**Comment by p-groarke** [comment]
I'll leave this open. You can ping me once the fixes are in.

**Comment by CookiePLMonster** [comment]
Sounds good! Do you know how do they even accept PR's, though? Looks like the git repository on GitHub is just a mirror, and an actual master repository is on hg, which I'm not familiar with.

**Comment by p-groarke** [comment]
Yeah they use mercurial. Its pretty similar to git from what I remember. Other than that can't really help you, sorry. I think they have a dev guide though.

**Comment by CookiePLMonster** [comment]
I have now submitted a patch for this mapping:
https://bugzilla.libsdl.org/show_bug.cgi?id=4504

Fingers crossed it gets answered in a timely manner!

**Comment by CookiePLMonster** [comment]
Seems like the fix has been accepted upstream:

https://bugzilla.libsdl.org/show_bug.cgi?id=4504#c1
https://hg.libsdl.org/SDL/rev/3d2042ac4ab9

**Comment by p-groarke** [comment]
Great! Once SDL 2.0.10 releases, I'll update our SDL mappings and the fix will roll in. Thx for going through the process :)
