### ISSUE TITLE
Pro Controller GUID is missing

### ISSUE THREAD

**Issue by marijnvdwerf** [gabomdq/SDL_GameControllerDB#250]
My Splatoon 2-edition Nintendo Switch Pro Controller (on macOS) has a different GUID from the one that is included in the database

```
030000007e0500000920000000000000 # in the database
030000007e0500000920000001000000 # GUID reported by SDL2 Gamepad Tool
```

**Comment by p-groarke** [comment]
Please run one of the linked config tools and send a PR with your controller. Thanks!
