### ISSUE TITLE
Nintendo Switch Pro Controller might have incorrect mappings

### ISSUE THREAD

**Issue by javmarina** [gabomdq/SDL_GameControllerDB#255]
Nintendo Switch Pro Controller, GUID 030000007e0500000920000000000000, Windows 10
I have been using the https://github.com/williamahartman/Jamepad library, which takes mappings from this database. Everything seems to be working fine, except A, B, X and Y. When I press A, it's recognized as B (and vice versa). When I press X, it's as I had pressed Y (and vice versa).
The current mapping for this controller is:
030000007e0500000920000000000000,Nintendo Switch Pro Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b2,y:b3,platform:Windows

That means:
- A is button 0 (should be 1)
- B is button 1 (should be 0)
- X is button 2 (should be 3)
- Y is button 3 (should be 2)

Here you can see an example of the correct mapping: https://answers.unity.com/questions/1419842/nintendo-switch-pro-controller-mapping.html
Button layout: https://s2.thcdn.com/productimg/600/600/11396097-7804615740625038.jpg

**Comment by offalynne** [comment]
this is actually working as intended. the inputs are mapped based on button position (relative to an Xbox360 controller), so a/b and x/y are swapped on the nintendo controller layout.

**Comment by p-groarke** [comment]
Yes it's working as intended. The database matches the button position, not the name. It gets confusing for the nintendo controllers as they are named identically to the xbox controller.

**Comment by javmarina** [comment]
Why then when I press A it is recognized as B? I don't understand if it's a problem with the controller this library or Jamepad library.

**Comment by offalynne** [comment]
That’s correct, yes. The format goal of this DB (and SDL2) is based on normalising the physical location of buttons on the controller. B on an XInput controller is the right face button, even though it is marked as A on Nintendo controllers. Physical button location/equivelance is given precedent to the letter labels. For example, on Sony controllers, the Circle button would be marked in the DB as B. Getting the device labels to match is not the goal of this repo; doing so requires an additional step (that’s out of scope for this DB) of identifying the controller type and how it’s buttons are labelled. I can’t speak to Jamepad as I don’t know what it purports to accomplish. See the Readme for more examples.
