### ISSUE TITLE
PS3 controller left trigger stays pressed on moonlight-embedded

### ISSUE THREAD

**Issue by Pakoach** [gabomdq/SDL_GameControllerDB#265]
Hello,

I noticed an issue with the PS3 mapping on moonlight-embedded and then I noticed that it was actually using the mappings from here.
I already opened an issue on irtimmer/moonlight-embedded but without any answer yet and I thought that it might be better to solve the issue directly here.

The issue is that the left trigger stays pressed after the first time I press it.
If I change the mapping, this issue disappears so I think that it comes from an incorrect mapping.

In the current mapping, for the PS3 controller I use () I have these values for the triggers: lefttrigger:a2,righttrigger:a5.
It works fine when I change it to lefttrigger:b6,righttrigger:b7.

Here is the mapping that works perfectly:
`050000004c0500006802000000810000,Sony Computer Entertainment Wireless Controller,a:b0,b:b1,x:b3,y:b2,start:b9,guide:b10,back:b8,leftstick:b11,rightstick:b12,leftshoulder:b4,rightshoulder:b5,dpup:b13,dpleft:b15,dpdown:b14,dpright:b16,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:b6,righttrigger:b7,platform:Linux`

Would you like me to submit a PR?

Do not hesitate to ask if you need more information.

**Comment by offalynne** [comment]
It's a problem with the device driver unfortunately, or possibly your controller (the trigger may not be calibrated properly). Generally speaking the equivalent button results for a given input provide a more reliable result when both are available, but the SDL spec (and users of this database) seem to prefer the analogue results on analogue inputs (ie. triggers) where they are available.

**Comment by Pakoach** [comment]
I am not sure to understand how to for to this conclusion.
As i said in the first message, changing the mapping seems to solve the issue.
Also I actually have 2 PS3 controllers, both with the same uid and both have the same issue so I don't think the problem comes from the device...

**Comment by offalynne** [comment]
In that case feel free to submit your mapping via PR for approval.

**Comment by Pakoach** [comment]
I created a pull request: https://github.com/gabomdq/SDL_GameControllerDB/pull/266

**Comment by p-groarke** [comment]
As I mention in your PR, this will have to go through the SDL project. Please come back here and ping once it is merged :)

**Comment by CookiePLMonster** [comment]
I'm not convinced this is a good solution, as it kills pressure sensitivity of triggers. Unless your device is a bootleg gamepad and doesn't have analog triggers?

**Comment by Pakoach** [comment]
My devices are official PS3 controllers. One came with the PS3 and I bought the second one afterwards. So I guess they should have pressure sensitivity.
Then maybe @offalynne was right and it could be an issue with the driver...
Honestly I don't how all this is working together. I never took a look at the code of the driver nor the SDL library...
I opened an issue at SDL. I hope someone there will understand the issue and propose a way forward...
@CookiePLMonster if you have any idea yourself, do not hesitate to share.

Here is the link to the issue FYI
https://bugzilla.libsdl.org/show_bug.cgi?id=4686
