### ISSUE TITLE
PS3 controller should support analog triggers.

### ISSUE THREAD

**Issue by stolk** [gabomdq/SDL_GameControllerDB#28]
The PS3 controller, according to wikipedia, has analog triggers.
(Dualshock 3 controller.)
http://en.wikipedia.org/wiki/DualShock

Yet, in the DB, the ps3 controller triggers are mapped to buttons?

Currently, I am getting digital values from the ps3 gamepad under SDL2, even with the SDL_GameControllerDB .txt file loaded.
Tested under OSX.

**Comment by looki** [comment]
Did you test if the PS3 controller has axes with a more general purpose gamepad library? It's not uncommon that trigger axes are reported as boolean value. For example, on Windows, I have a Logitech controller that does this in its DirectInput mode, but you get proper axis values in XInput mode (it has a switch for both modes). It might just be a driver limitation.
