### ISSUE TITLE
NEXT SNES Controller right shoulder mapping is wrong

### ISSUE THREAD

**Issue by leiradel** [gabomdq/SDL_GameControllerDB#289]
This controller's right shoulder is mapped to button 6, but the corresponding `SDL_Joystick` reports button 5 being pressed when I press the right shoulder.

Changing the mapping to `rightshoulder:b5` solves the issue.

**Comment by offalynne** [comment]
Which GUID?

**Comment by leiradel** [comment]
Sorry, it's `030000001008000001e5000010010000`.

**Comment by p-groarke** [comment]
Please open a PR with the fix, thank you.
