### ISSUE TITLE
Why are the recommended mappings the way they are?

### ISSUE THREAD

**Issue by aaronfranke** [gabomdq/SDL_GameControllerDB#292]
Some of the [recommended mappings](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/data/mapping_guide.png) don't make much sense to me.

* Arcade: Why is RB/RT to the left of LB/LT?

* SEGA: Why is it this way? Typically one would use shoulder buttons with the other shoulder button, such as navigating left/right between menus, and it doesn't make sense for LB to navigate left and Z to navigate right. Also, the triggers are really weird this way, in a shooter game this means you have to physically press RB to aim and press C to fire, which is **not feasible** if you're using the right thumb for aiming. I think it would make far more sense if LB was LT, RB was RT, Z was LB, and C was RB.

* GameCube: Since it doesn't mimic the traditional diamond shape, why try and force the diamond positions onto the controller? I think it would make a lot more sense if B was kept as B etc.

Also, there are mappings which do not conform to this layout, for example I know of [this one](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L52) (https://github.com/gabomdq/SDL_GameControllerDB/issues/77).

**Comment by p-groarke** [comment]
Fighting games.

We've answered similar concerns in the past. Since this is a community DB, it is **guaranteed** to have incorrect mappings. As such, developers should offer remapping capabilities.

So what is important isn't the layout, it's that it is standardized. Since you can remap to your liking in the games you play.

**Comment by aaronfranke** [comment]
> We've answered similar concerns in the past. 

To be fair, I couldn't find any such issues by searching.

Makes sense, I still think the default layout should be sensible, but if it works for fighting games then at least it makes sense somewhere.

**Comment by offalynne** [comment]
The default matches the modern Hori standard. It's not actually an active concern but I'm curious: which SEGA controller has six face buttons and a right thumbstick exactly?

> there are mappings which do not conform to this layout
fix them! :-)

in the case of the battalife joystick, feel free to PR the upstream SDL db, or at least post the fix here for posterity?
