### ISSUE TITLE
Where do the "h0.4", etc. strings come from?

### ISSUE THREAD

**Issue by namandixit** [gabomdq/SDL_GameControllerDB#298]
It is not obvious where the input strings (`b0`, `h0.4`, `a1`, etc.) come from. On Linux, for example, what we actually get are enums (`BTN_EAST`, `ABS_HAT0X`, `ABS_X`, etc.). I am sure that other platforms will have their own means of identifying various buttons, etc. Since this repo is targeted towards developers, will it be possible to add some information on how to actually use this database in an engine?

**Comment by p-groarke** [comment]
Hi namandixit,
The instructions to use the DB are on the SDL wiki  : https://wiki.libsdl.org/SDL_GameControllerAddMappingsFromFile

It is meant to be used with SDL, though other engines also support it. The h values (hats) are an enum in SDL for d-pad directions. But you shouldn't have to interact directly with those, SDL will parse the DB and you would use SDL APIs.

**Comment by namandixit** [comment]
I see, I will go read how that function works. Regardless, it might be worth it to write some basic introductory documentation so that people who aren't using SDL can also take advantage of these mappings (especially since SDL's source doesn't seem readable either, globals abound!). Unless I am completely mistaken, it probably wouldn't be any more complicated than a simple mapping of ids/enums to strings.

**Comment by p-groarke** [comment]
Well this project is just a collection of mappings. Each engine that supports the format will write their own documentation. Basically, you import the mappings, and then use an engine's/library's existing controller APIs. You shouldn't have to work with the mappings directly, unless you are writing your own engine.

**Comment by namandixit** [comment]
No, what I mean is that it should proabably be documented what `b0`, etc. actually stand for. For example, on my Dualshock 4 CUH-ZCT2E controller, this seems to be the mapping between the strings used in the DB and Linux's `evdev` enums:

```
b0 = BTN_SOUTH
b1 = BTN_EAST
b3 = BTN_WEST
b2 = BTN_NORTH

h0.4 = ABS_HAT0Y (Value -1)
h0.8 = ABS_HAT0X (Value -1)
h0.2 = ABS_HAT0X (Value 1)
h0.1 = ABS_HAT0Y (Value 1)

b11 = BTN_THUMBL
b12 = BTN_THUMBR

a2 = ABS_Z (analog), BTN_TL2
a5 = ABS_RZ (analog), BTN_TR2

b4 = BTN_TL
b5 = BTN_TR

b8 = BTN_SELECT
b10 = BTN_MODE
b9 = BTN_START

a0 = ABS_X
a1 = ABS_Y
a3 = ABS_RX
a4 = ABS_RY
```
Obviously, I don't have enough knowledge regarding this DB to know if this mapping is global or just valid on my machine/controller. But I hope you can see how providing a little bit of this kind of documentation can really help those who aren't using SDL.

**Comment by p-groarke** [comment]
You'll have to take it up to the SDL project. They define the format and write the parser.
