### ISSUE TITLE
8bitdo SN30/SF30 Pro controller axes and buttons wrong.

### ISSUE THREAD

**Issue by MarcoLizza** [gabomdq/SDL_GameControllerDB#306]
In the current release, the 8bitdo controllers SN30/SF30 Pro/Pro+ aren't properly recognized, and buttons are swapped.

See the attached file for a fixed mapping.

[gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/files/4019796/gamecontrollerdb.txt)

**Comment by offalynne** [comment]
this is super vague, please point out the relevant GUID/line numbers

**Comment by offalynne** [comment]
existing maps are tested and working correctly, looks like you need to update your firmware.

**Comment by offalynne** [comment]
can confirm your right stick changes are correct on the SN30 Pro+ so i'm glad to submit those myself, but i'm hesitant to change every one of the SN30 Pro Linux maps as those GUIDs represent multiple revisions and firmware versions and i don't have a device on hand to compare.

if you can use on of the configurator programs linked in the readme and confirm the axis changes with you own SN30 Pro device, feel free.

**Comment by MarcoLizza** [comment]
> please note that inputs match button position layout relative to the xbox controller standard, so a/b and x/y are the other way round on 8bitdo pads

I read it in the mapping guide. Anyhow, since the 8bitdo SN30 (and similar ones) displays X/Y and A/B on the controller faceplate, why the mapping shouldn't match them?

> if you can confirm your firmware is up to date and your own mapping matches the db format, please file a PR with your changes.

Thanks, I will provide it as soon as possible.

> your right stick changes seem correct to me on _some_ of the SN30 Pro+ maps, but wrong on others. i'm glad to submit the relevant changes myself, but i'm hesitant to change every one, especially the SN30 Pro Linux, maps as those GUIDs represent multiple revisions and firmware versions and i don't have a device on hand to compare.

Personally, I can check and assess the mapping for the SF30 Pro. I assumed that the SN30 Pro only differs in the chassis color.

I'll double check for both Windows a Linux and provide a mapping for this controller only (the other were mere assumptions I made, I must admit).

**Comment by offalynne** [comment]
great, thanks for clarifying.

> since the 8bitdo SN30 (and similar ones) displays X/Y and A/B on the controller faceplate, why the mapping shouldn't match them?

because that's how the repo works. the labels in the DB refer to physical button location, not faceplate labels.

**Comment by MarcoLizza** [comment]
> because that's how the repo works. the labels in the DB refer to physical button location, not faceplate labels.

I understand... but, still, I find confusing the in my application code I check for the X button to be pressed only to see that on the controller I need to press the Y button. And this can be seamlessly fixed but remapping the buttons. Doesn't mappings exist for this purpose?

**Comment by offalynne** [comment]
This repo only aims to match buttons based on physical location. There's a (stale) [branch that handles button labels](https://github.com/gabomdq/SDL_GameControllerDB/blob/buttons/buttonnamedb.txt) if you want to implement that yourself, otherwise it's left up to you how you'd like to do it. This repo is in service of SDL, which itself recognizes device type (and thereby button labels) with a different method.

**Comment by MarcoLizza** [comment]
> It's a little confusing to explain, sorry if I'm not being clear.

In fact, I'm still confused. :)

Out of couriosity, how does SDL recognizes/fixes this?

**Comment by offalynne** [comment]
By assigning controller type. From there you can make inferences about button label, ie. SDL 'A' is Cross on a PlayStation controller. https://hg.libsdl.org/SDL/file/d984274996dd/src/joystick/controller_type.h

The point of mapping the controller is so that upon picking up any device, default controls are as closely shared between different devices as possible, regardless of what he labels are.

**Comment by offalynne** [comment]
If you can confirm the map on your end for Linux using DInput mode (turn on controller with B + Start held), testing both over both Bluetooth and USB as they give different GUIDs, I'm able to confirm the rest, and will author a PR.

**Comment by MarcoLizza** [comment]
Thanks for the clarification. :)

> If you can confirm the map on your end for Linux using DInput mode (turn on controller with B + Start held), testing both over both Bluetooth and USB as they give different GUIDs, I'm able to confirm the rest, and will author a PR.

I'll confirm on Tuesday (once I'm back from vacation) and write you ASAP. Thanks!

**Comment by offalynne** [comment]
Sam Latinga has added a lot of 8BitDo device maps that will address this on rebase come next SDL release, so most of these are now unnecessary/redundant.

Sam’s maps don’t include the Pro+ so I’ll author a PR with those shortly.

I’m still curious about your SN30 Pro Linux GUIDs @MarcoLizza if you’re willing to provide them, given all the variants we’ve seen.

**Comment by offalynne** [comment]
SN30 Pro+ fixed in #310 and SN/SF30 Pro updated [upstream](https://hg.libsdl.org/SDL/log?rev=8bitdo+pro)

**Comment by p-groarke** [comment]
merged
