### ISSUE TITLE
hi i have a new controller to add not sure what to do with it though

### ISSUE THREAD

**Issue by grant2258** [gabomdq/SDL_GameControllerDB#308]
I got the output from test/controller.c

```
03000000ff1100003133000000000000,PC Game Controller,plat03000000ff1100003133000000000000,PC Game Controller,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b10,start:b11,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,-rightx:-a2,+rightx:+a3,righty:a4,lefttrigger:b6,righttrigger:b7,
form:Windows,a:b2,b:b1,x:b3,y:b0,back:b10,start:b11,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,-rightx:-a2,+rightx:+a3,righty:a4,lefttrigger:b6,righttrigger:b7,
```

**Comment by offalynne** [comment]
Can you provide a better description of the device? Manufacturer/product name? Perhaps a link to a site selling the product?

**Comment by p-groarke** [comment]
The mapping is corrupted. What controller is this for?
The easiest way to get a mapping is using Steam. The instructions are on our readme.

**Comment by grant2258** [comment]
```
	"SDL_GamepadBind"		"03000000ff1100003133000000000000,dev:gen:Gear Pc control pad,platform:Windows,a:b2,b:b1,y:b0,x:b3,start:b11,back:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,leftstick:b8,rightstick:b9,
030000005e040000a102000000007801,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"
```
from steam config its a really old gear pc control pad

**Comment by p-groarke** [comment]
And what is the real name (brand/model)?

**Comment by grant2258** [comment]
the brand is Gamestation Gear mode is PC Control Pad its just that and a serial number on the back can take pics if you need them

**Comment by p-groarke** [comment]
Gamestation Gear is good enough. I'm guessing you have no experience with git?

**Comment by grant2258** [comment]
yea can put a commit in no problem just need to know the format im putting it in and where

**Comment by p-groarke** [comment]
OK. You can use the Steam mapping.
- Change the name from `dev:gen:Gear Pc control pad` to `Gamestation Gear`.
- Paste that in the db text file, somewhere in the Windows sections.
- Then run the format command (`python check.py --format gamecontrollerdb.txt`). It will sort the db and reorder the mappings to make it correct.
- Commit to your branch and open a PR. I will provide further assistance there if required.

Thanks for your contribution!

**Comment by p-groarke** [comment]
If I understand your question right, I wouldn't worry about the name it is generating. This is found through the drivers. Some models share the same "name" because internals are just rebranded, or it isn't detected right. The name doesn't really matter, it's just for us.

**Comment by grant2258** [comment]
I thought the right name might seperate if from the other driver its wrongly picking up is all. Ill go ahead and add it now.

**Comment by grant2258** [comment]
```
 python check.py --format gamecontrollerdb.txt
check.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  self.__keys = {k:v for (k,v) in self.__keys.items() if v is not ""}
check.py:206: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.__keys[button_key] is not "":

Applying checks.

Duplicate detected at line #314
Previous mapping at line #276
In mapping
03000000ff1100003133000000000000,GameStation Gear Pc control pad,a:b2,b:b1,y:b0,x:b3,start:b11,back:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,leftstick:b8,rightstick:b9,platform:Windows,
```

**Comment by p-groarke** [comment]
Going to have to fix the script, not sure what is happening there.

Unfortunately, your controller uses the same GUID than another one. We can't do anything about it (sorry). I would bring up the issue in the SDL forums. As far as I know, it's been brought up before and I don't think a fix was ever found. Ultimately, I believe it is a manufacturer's issue.

**Comment by grant2258** [comment]
ill just add some code to map this myself in my code. A lot of chines makers do this as well accept they use the same name as well. Fortunaly the name is at least different in this case thanks for taking the time to help me with this is any other controllers that need added i know what to do
