### ISSUE TITLE
PSA: DMCA takedown issued by p-groarke (Philippe Groarke)

### ISSUE THREAD

**Issue by gabomdq** [gabomdq/SDL_GameControllerDB#323]
Please be aware that this repository might get taken down temporarily by Github due to a DMCA takedown issued by former contributor p-groarke (Philippe Groarke). A few days ago, after being denied admin access to this repo by me, Groarke tried to hijack the repository (see https://github.com/gabomdq/SDL_GameControllerDB/issues/318), and now since he's been removed as contributor he's trying to take down the repository with a bogus copyright claim.

I originally granted p-groarke contributor access here to help with maintenance and essentially help merge PRs since I didn't have enough time to do so myself and the backlog was growing quickly thanks to all the awesome community contributions.
Sadly, unbeknownst to me, he unlawfully (in violation of item 3 of the license) inserted himself as copyright holder in the LICENSE file and check.py, and now he's trying to use this unauthorized modifications as reason for the DMCA takedown. When I created this database, I chose to not take copyright and instead assigned all copyright to Sam Lantinga (SDL's creator) and matched SDL's license, with the intention of providing familiarity to users and clearly indicate that this was going to be done in the best spirit and traditions of the open source community.

You can see p-groarke inserting himself in the copyright here: https://github.com/gabomdq/SDL_GameControllerDB/commit/07006fccbc359fab674f5eccb15288a61ebc3b22#diff-9879d6db96fd29134fc802214163b95a and here on check.py https://github.com/gabomdq/SDL_GameControllerDB/commit/ede68a4d1740881baee4804b3341d1c291bf773f#diff-80ee07c6b10902b1bae15660a736de65 a file that was contributed originally by user meghprkh

I filed a DMCA counter notice but I don't know what process Github follows, so if you see this repository taken down just know it's because of this issue and that we'll hopefully be back online soon!

And since we are here, thanks to all the awesome contributors that have created this database and made it so popular!

**Comment by Akaricchi** [comment]
:popcorn:

**Comment by AliceLR** [comment]
Has the DMCA takedown been resolved? The repository seems to be public again but GitHub hasn't fixed the forks (mine is now pointed to https://github.com/inequation/SDL_GameControllerDB).

**Comment by gabomdq** [comment]
I'll contact Github.

**Comment by gabomdq** [comment]
Everything should be back to normal, though I had to force push the repo to remove the claimed content from the git history according to Github guidelines, just in case.

**Comment by lightningterror** [comment]
Glad everything got resolved in the end.
