### ISSUE TITLE
add version informations in gamecontrollerdb.txt?

### ISSUE THREAD

**Issue by XenoAmess** [gabomdq/SDL_GameControllerDB#327]
How about adding a version head comment in gamecontrollerdb.txt to give user a better view of what version of this db is?
right now it only contains data format version.
It sometimes make me confused as I do not have a easy way to know how my using version of gamecontrollerdb.txt is older than your latest version.
(for example, git commit hash or daytime or semver)

**Comment by gabomdq** [comment]
Do you have a solution in mind that does not involve manually updating the file with this information?

**Comment by XenoAmess** [comment]
> Do you have a solution in mind that does not involve manually updating the file with this information?

I remember you have a sort.py to sort the db.txt everytime after the edit...
and sort.py shall be run everytime editting the db.txt
So how about modify sort.py and let it change the version comment in db.txt?

**Comment by XenoAmess** [comment]
damn it I forget the deletion of sort.py...
Do you need me write a sorter code?
Although I'm afraid I can only make a java one.
I hate python.

**Comment by Florin9doi** [comment]
> Do you have a solution in mind that does not involve manually updating the file with this information?

git hooks
