### ISSUE TITLE
XInput mapping is wrong for SDL 2.0.4

### ISSUE THREAD

**Issue by slime73** [gabomdq/SDL_GameControllerDB#33]
SDL 2.0.4 changes the Windows XInput joystick layout. Its default mapping string for XInput controllers has been changed to reflect that, but this database is still using the old layout for its XInput mapping string.

Here's the comparison:

SDL 2.0.4:
```
xinput,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,
```

This database:
```
xinput,X360 Controller,a:b10,b:b11,back:b5,dpdown:b1,dpleft:b2,dpright:b3,dpup:b0,guide:b14,leftshoulder:b8,leftstick:b6,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b9,rightstick:b7,righttrigger:a5,rightx:a2,righty:a3,start:b4,x:b12,y:b13,platform:Windows,
```

Since SDL always includes an XInput mapping in Windows (when built with XInput support enabled), it might make sense to just drop the old XInput mapping from this database.

**Comment by gabomdq** [comment]
Done! Thanks!
