### ISSUE TITLE
cannot find my controllers in the db

### ISSUE THREAD

**Issue by beaumanvienna** [gabomdq/SDL_GameControllerDB#331]
Hi, I wrote a small test program to detect my controllers, but the GUIDs don't match anything in the database. I have a PS3 controller, a Wiimote, and an Afterglow Xbox 360 controller.

[out-2.0.10.txt](https://github.com/gabomdq/SDL_GameControllerDB/files/4424968/out-2.0.10.txt)

Maybe just old hardware?

**Comment by gabomdq** [comment]
030000006f0e00001301000002010000 is not in the database, 050000004c0500006802000000800000 is in the database so it should be picked up (assuming you are loading up this db in your program).
Entries not in the database can be submitted via PR.
