### ISSUE TITLE
Wiimote entry 

### ISSUE THREAD

**Issue by beaumanvienna** [gabomdq/SDL_GameControllerDB#337]
The Wiimote entry under Linux is funny. Why should it have a left or right shoulder / trigger / stick? 

"05000000010000000100000003000000,Nintendo Wiimote,
a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b2,y:b3,platform:Linux,"

The actual Wiimote device has only 11 buttons. But then there are three more devices associated with the controller, the Accelerometer, IR, and Motion Plus. These do provide hats and axis, but that's just sensor data. I was wondering where the above entry comes, but then I found in the SDL sources. To me, it looks like it should be removed. Unfortunately, my Wiimotes have a different guid, so I wouldn't be 100% sure.

In general, do you guys have any experience with the Wiimote and SDL? What about the Nunchuck and SDL?

**Comment by offalynne** [comment]
whatever the pairing method or mapping choices, that’s a pretty bogus looking GUID! you should inquire in the SDL forums if you’re looking for follow up as the upstream maps are not modified in this project. 

SDL doesn’t have any special treatment of Wii remotes in particular; if it shows up as a HID and works in, for example, jstest, it should work fine in SDL. if you can pair your device properly and get a usable map with unique GUID feel free to submit it here.
