### ISSUE TITLE
purge redundant mappings from official repo

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#364]
since losing `sort.py` a lot has changed upstream in SDL including

- Android maps changing format
- alternative maps for controllers with Nintendo-style layout (using `hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS`)
- myriad new devices added (this db is now long behind SDL's)

since it doesn't seem like there has been any movement toward authoring a new CI check to handle parity, i think would best to consider this DB purely additive and remove maps that are redundant with upstream data

this should help prevent a duplication of effort, and encourage people who have issues with upstream SDL maps to take them upstream

to prevent further barriers to contribution, no need to force an automatic check or similar -- an occasional manual purge of matching upstream GUIDs  should suffice. if @gabomdq's fine with this direction i'll author a PR that removes all present GUIDs that match upstream, and make note of this change in the readme

**Comment by gabomdq** [comment]
We'll keep the "redudant" mappings for now, my intention is that this DB is a superset of what SDL includes in their binaries, useful for people that want to update mappings without having to rebuild or update SDL. Also, it seems that these mappings are not just used by SDL but also parsed independently by Godot, so there's no gain in removing mappings.

**Comment by offalynne** [comment]
A number of projects do indeed use this DB without SDL, but if it's to be a superset the mapping list needs maintaining since it's fallen significantly behind the SDL mappings. Issues like the recent PR that breaks official PS3 controllers on Windows should also presumably be avoided?
