### ISSUE TITLE
Allow stick tilts to be configured before stick presses

### ISSUE THREAD

**Issue by JapanYoshi** [gabomdq/SDL_GameControllerDB#365]
I have an 8BitDo Lite, where the sticks are physically D-pads, and a stick press is configured as Stick U+D+L+R. The UI makes it impossible for me to configure stick presses and stick tilts correctly.

I think the config string should be

    030000005e0400008e02000000007801,8BitDo Lite,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,

, but have no way of importing the mapping string.

**Comment by JapanYoshi** [comment]
In addition, I cannot locate where these custom mappings are stored on disc. I can't fix the mistakes with the GUI, so I have to change the data directly. Where are the custom mappings?

**Comment by gabomdq** [comment]
SDL has a very helpful community, you should ask these things there: https://discourse.libsdl.org/

**Comment by JapanYoshi** [comment]
That doesn't address the problem.

**Comment by gabomdq** [comment]
We don't make a UI, we don't determine the SDL controller format and we don't decide where the mappings are stored. This repository just provides a database for game developers to use.
