### ISSUE TITLE
Update from SDL

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#367]
Repo is over 9 months and 41 PRs behind the SDL repo's DB as of current

**Comment by gabomdq** [comment]
If you have a PR for this please open it, if not please don't open an issue for this. The goal here is not to track what SDL is doing.

**Comment by offalynne** [comment]
>my intention is that this DB is a superset of what SDL includes

...

**Comment by offalynne** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/pull/368
