### ISSUE TITLE
Incorrect mapping for Playstation 4 Wireless controller CUH-2CT2E on Android

### ISSUE THREAD

**Issue by MicrosoftComments** [gabomdq/SDL_GameControllerDB#379]
The mapping for 050000004c050000cc090000ffff3f00 is incorrect on the two Android devices I used (Fire Tablet & a generic set top box).

If it's made identical to 050000004c050000cc090000fffe3f00 then it works fine:

050000004c050000cc090000ffff3f00,PS4 Controller,a:b1,b:b17,back:b15,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b3,leftstick:b4,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b18,rightstick:b6,righttrigger:a4,rightx:a2,righty:a5,start:b16,x:b0,y:b2,

Using SDL2-2.0.12

**Comment by MicrosoftComments** [comment]
The plot thickens.

Got my hands on some more Android devices, and the old mappings are correct when bluetoothed to a Samsung Galaxy J5, and the new mappings are wrong. Switch back to the Fire Tablet, and suddenly the new mappings are right and the old ones are wrong.
This is with a genuine Sony Dualshock Wireless controller, not some odd third-party device with multiple modes.

The problem seems to be that somehow the same controller (and it is literally the same controller) is being read differently depending on the device it's attached to. Both mappings are correct on some devices, and wrong on others. The controller system reports them both as the same device, but goes on to treat them differently.

**Comment by offalynne** [comment]
Check kernel version between the devices

**Comment by MicrosoftComments** [comment]
Oh the Android versions are waaaay apart. The set-top box is Android 4.4/19, the Fire Tablet is 5.1.1/21 and the Galaxy is 9/28. I'm guessing at some point between 21 and 28 the underlying mechanism changed somewhere.
I'll do some more investigation and see what I can find, and if it is as neat as 'in Android version xx we changed how Bluetooth controllers map their buttons' 
I'm not generating mappings, I'm using mappings from the database. Both versions are in there under different IDs for the Playstation 4 Wireless Controller (which still claims to be Wireless even when it's plugged in)

**Comment by offalynne** [comment]
> I'm not generating mappings
how are you testing them?

>  if it is as neat as 'in Android version xx we changed how Bluetooth controllers map their buttons'
very likely the case, and would be useful to know. https://android.googlesource.com/kernel/common.git/+log/brillo-m9-release/drivers/hid/hid-sony.c

**Comment by Swyter** [comment]
Probably these things and [`9131f8cc2b4eaf7`](https://github.com/torvalds/linux/commit/9131f8cc2b4eaf7c08d402243429e0bfba9aa0d6) (28 Nov 2016) have something to do with this:

> https://github.com/torvalds/linux/blob/16bc1d5432ebd8e50e480eb300fd2b84afa28286/drivers/hid/hid-sony.c#L2876-L2883


Sounds like the problem exists because those Android devices use a kernel version shipped after the new Sony HID driver being originally introduced *but* before the SDL2 fix made it in the tree.

I wonder if this could be amended in SDL2 itself with a quirk to check the current Linux kernel version and manually patch the USB version like the current driver does:
```c
	/* Patch the hw version on DS3/4 compatible devices, so applications can
	 * distinguish between the default HID mappings and the mappings defined
	 * by the Linux game controller spec. This is important for the SDL2
	 * library, which has a game controller database, which uses device ids
	 * in combination with version as a key.
	 */
	if (sc->quirks & (SIXAXIS_CONTROLLER | DUALSHOCK4_CONTROLLER))
		hdev->version |= 0x8000;
```

If I'm `git blame`ing correctly, DS4 support was introduced in [`0bd88dd3dd5e73`](https://github.com/torvalds/linux/commit/0bd88dd3dd5e73e5d43b8d1e7a96b841978df562), but that only adds rumbling support, so we should check for the first commit that actually starts changing the layout.

So from `v3.14-rc1`+ to `v4.10-rc1`, I think.

**Comment by Swyter** [comment]
Probably these changes; first one replaces the USB HID descriptor, the second one changes the Bluetooth one:

https://github.com/torvalds/linux/commit/ed19d8cf28b2b03ec05e75de9c1f73981b342978 (`v3.14-rc1`+)
https://github.com/torvalds/linux/commit/d829674d29d7eb99aeb3ad11eba61d06cda7aff4 (`v3.15-rc1`+)

Let me know what you guys think.

**Comment by offalynne** [comment]
From various bug reports elsewhere it looks like the old maps were broken in Android 8 and fixed (with new mappings) in 9.

**Comment by offalynne** [comment]
https://android.googlesource.com/platform/frameworks/base/+/0a5109d955935e16b71812ec3c25c0e63d646e19

**Comment by MicrosoftComments** [comment]
I've started logging more kernel versions along with Android SDK versions, but so far my rule of thumb of 'use the a:b0 map for SDK version 23+, otherwise use a:b1' hasn't caused any reported complaints.
I am monitoring this, but there are so many variations on the Android devices, and I only have access to a fraction of them.

**Comment by offalynne** [comment]
Aha. https://github.com/aosp-mirror/kernel_common/commit/9131f8cc2b4eaf7c08d402243429e0bfba9aa0d6

Looks like this made it into Android 5.4, so API level 23+ should be right.

**Comment by offalynne** [comment]
Thinking about the correct path forward here. SDL jettisoned the old-format Android maps from their DB a while ago, and while they remain in this DB for posterity they are probably most helpful if kept up to date.

I think the correct steps are
- identify Android GUIDs impacted by kernel difference
- update relevant maps to reflect correct functionality on the latest Android kernel
- make note on relevant PR(s) about the intent of the change to help anyone encountering the issue in the future

**Comment by MicrosoftComments** [comment]
Another data point, which has a surprisingly high API level and recent Kernel version:

This device uses the old mapping: HCH03 - Android 26 - Kernel 4.9.44_hi3796mv200
This (quite similar) device uses the new mapping: HPH07 - Android 28 - Kernel 4.9.116_hi3798mv2x

**Comment by offalynne** [comment]
More reliable Android mapping depends on SDL better handling the state of key layout files, in the meantime #462 brings the out of date map addressed in this issue up to spec.
