### ISSUE TITLE
Mapping string for Logitech Wingman Rumblepad

### ISSUE THREAD

**Issue by prusswan** [gabomdq/SDL_GameControllerDB#405]
The gamepad tool is not able to detect/map the right stick properly, so manual override is required:

> 030000006d0400000ac2000000000000,WingMan RumblePad,platform:Windows,a:b0,b:b1,x:b3,y:b4,back:b8,guide:b5,start:b2,lefttrigger:b6,righttrigger:b7,dpup:-a1,dpdown:+a1,dpleft:-a0,dpright:+a0,-leftx:h0.8,+leftx:h0.2,-lefty:h0.1,+lefty:h0.4,-rightx:-a3,+rightx:+a3,-righty:-a4,+righty:+a4,

Depending on the game, `lefttrigger/righttrigger` can be changed to `leftshoulder/rightshoulder` as needed

**Comment by offalynne** [comment]
Can you please arrange the map in the Hori Fightpad format: https://stores.horiusa.com/fighting-commander-octa-designed-for-xbox-series-x-s-xbox-one/

So C is righttrigger and Z rightshoulder, triggers are leftshoulder (left) and lefttrigger (right).

Thanks!

**Comment by prusswan** [comment]
>  Hori Fightpad format

Not sure what is needed here? This controller only has one set of shoulder buttons, so it has to be a choice between shoulder/trigger.

**Comment by offalynne** [comment]
Does it have 6 face buttons?

**Comment by prusswan** [comment]
> 
> 
> Does it have 6 face buttons?

Yes, XYZ and ABC on two rows

**Comment by offalynne** [comment]
The format for six-button pads in this db matches the Hori six button layout described above.

**Comment by prusswan** [comment]
Okay, mapping string following that layout:

030000006d0400000ac2000000000000,WingMan RumblePad,platform:Windows,a:b0,b:b1,x:b3,y:b4,back:b8,leftshoulder:b6,rightshoulder:b5,lefttrigger:b7,righttrigger:b2,dpup:-a1,dpdown:+a1,dpleft:-a0,dpright:+a0,-leftx:h0.8,+leftx:h0.2,-lefty:h0.1,+lefty:h0.4,-rightx:-a3,+rightx:+a3,-righty:-a4,+righty:+a4,

**Comment by offalynne** [comment]
Which OS platform is this for?
