### ISSUE TITLE
Android database is missing

### ISSUE THREAD

**Issue by mittorn** [gabomdq/SDL_GameControllerDB#41]
Android uses first 16 bytes of controller name as guid, so i suggest to add converted controller database for android platform (have not tested yet):http://pastebin.com/Jrb6kB0d
This is a conversion script that can be used to update list:
http://pastebin.com/SKj4hXFQ
If anyone have controllers conneted to android device, please test it.

**Comment by gabomdq** [comment]
Android does its own controller mapping, so all controllers with proper system drivers should behave the same as far as I know.
