### ISSUE TITLE
Please add ACRUX gamepad

### ISSUE THREAD

**Issue by the-LONS-network** [gabomdq/SDL_GameControllerDB#429]
Heres the strings
`03000000c01100000355000011010000,ACRUX USB GAME PAD,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,platform:Linux,`

`03000000c01100000355000011010000,ACRUX USB GAME PAD,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,platform:Windows,`

**Comment by the-LONS-network** [comment]
Also who the hell dmca ed the check.py file?

**Comment by offalynne** [comment]
@the-LONS-network you can use SDL's if you're so inclined in the future: https://hg.libsdl.org/SDL/file/default/src/joystick/sort_controllers.py
