### ISSUE TITLE
DragonRise Controller 03000000790000000600000010010000 wrong right stick x/y

### ISSUE THREAD

**Issue by varlesh** [gabomdq/SDL_GameControllerDB#438]
This used for Defender Omega.
lsusb:
`ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad`
Right stick used wrong settings 
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L562

Right mapping:
- rightx:a2
- righty:a3

Wrong mapping:
- rightx:a3
- righty:a4

**Comment by varlesh** [comment]
i can send PR, if needed

**Comment by offalynne** [comment]
This is a problematic GUID with a lot of conflicting device mappings. I suggest taking it upstream to
