### ISSUE TITLE
add mapping for Betafpv LightRadio 2 SE

### ISSUE THREAD

**Issue by ThomasKuehne** [gabomdq/SDL_GameControllerDB#445]
83042143000000000000504944564944,BETAFPV JoyStick  ,platform:Windows,x:a5,y:a6,rightshoulder:a4,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a7,

[Betafpv LightRadio 2 SE](https://betafpv.com/products/literadio-2-se-radio-transmitter)

**Comment by offalynne** [comment]
See https://github.com/gabomdq/SDL_GameControllerDB/issues/446#issuecomment-798786158, feel free to add comment or make a PR if you get the correct GUIDS
