### ISSUE TITLE
add mapping for Jumper T-Lite Radio Transmitter

### ISSUE THREAD

**Issue by ThomasKuehne** [gabomdq/SDL_GameControllerDB#446]
0912544f000000000000504944564944,Jumper TLite Joystick,platform:Windows,leftx:a3,lefty:a2,rightx:a0,righty:a1

**Comment by offalynne** [comment]
You're using old software, these GUIDs are out of date. Please use this to generate your mappings http://www.generalarcade.com/gamepadtool/
