### ISSUE TITLE
PS5 DualSense right stick up/down not working

### ISSUE THREAD

**Issue by adamfirst1986** [gabomdq/SDL_GameControllerDB#448]
Hello, I have a problem with DualSense right stick. For some reason, up/down just doesn't work and stays pressed while in game.
Here's how it looks in gamepad tool: https://gfycat.com/shadyjointaltiplanochinchillamouse
Maybe there's a way to fix this? I'm on macOS, everything else works very well
Thank you for making this!

**Comment by offalynne** [comment]
You might have a look with another tool to better see what’s going on there:
https://apps.apple.com/ca/app/controllers-lite/id673660806
or
https://greggman.github.io/html5-gamepad-test/

**Comment by offalynne** [comment]
Either way you’d be best to take this upstream to SDL if the problem persists for you, the mapping tool is built on quite an old version of SDL and the problem does not look mapping related.

**Comment by adamfirst1986** [comment]
I'm on MacOS Mojave. USB and BT, it's the same result for both
I used gerggman website to test it out and it shows that it works

**Comment by offalynne** [comment]
Perhaps try running through the mapping wizard in the testing app to see if you can get a correct map? The linked tester is built with quite an old version of SDL, the one that’s bundled with source may serve you better

**Comment by adamfirst1986** [comment]
How can I do this? Sorry, I just don't know much about this

**Comment by offalynne** [comment]
![Uploading 9611BAE6-9893-4DA4-9AB3-415CC08D899E.jpeg…]()

**Comment by adamfirst1986** [comment]
Oh! I tried this two times, but it didn't work before
But now after I pressed reset environment variable, restarted computer and tried this again, it now works!
Up and down are now working, thank you so much for your help!!

**Comment by offalynne** [comment]
Can you paste the mapping string you got here, please?

**Comment by adamfirst1986** [comment]
This one?

"Sony DualSense2", 030000004c050000e60c000000010000 (mapping available)
Environment variable "SDL_GAMECONTROLLERCONFIG" is set to: "030000004c050000e60c000000010000,Sony DualSense2,platform:Mac OS X,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b12,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,
"

**Comment by offalynne** [comment]
Fixed in #449
