### ISSUE TITLE
SDL_GameControllerDB on Ubuntu

### ISSUE THREAD

**Issue by olegharput** [gabomdq/SDL_GameControllerDB#454]
I am using ubuntu i wrote the same code as in 
https://www.youtube.com/watch?v=EQL6HZmRMx4&list=PLZVNxI_lsRW2kXnJh2BMb6D82HCAoSTUB&index=13

but it does not work(my output is "nil" not "true" using xbox360 controller).  As i remember one or two years ago the same code worked on Windows with the same machine and probably with the same controller. Is it normal? What must i do?
                                                                          Please help.

**Comment by offalynne** [comment]
https://love2d.org/forums/viewforum.php?f=4
