### ISSUE TITLE
Please add Joystick mapping

### ISSUE THREAD

**Issue by ViNi-Arco** [gabomdq/SDL_GameControllerDB#458]
Hi, heres the strings:

`03000000bd12000003c0000010010000,Joypad Alpha Shock,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,`

`03000000bd12000003c0000010010000,Joypad Alpha Shock,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Windows,`

**Comment by offalynne** [comment]
thanks, can you provide a photo or product link?

**Comment by ViNi-Arco** [comment]
Hello Mrs. Alynne, here photo  [1](https://user-images.githubusercontent.com/57958460/115495392-e8f4e380-a23d-11eb-920b-0596a0cae0e2.jpg) and [2](https://user-images.githubusercontent.com/57958460/115495427-fdd17700-a23d-11eb-8c45-55d0768f85ff.jpg) of Joypad Alpha Shock.

Specifications:
- Analog and Digital Mode
- Turbo function
- Vibration System
- 12 Buttons
- Connection: USB v.1.1/2.0

**Comment by ViNi-Arco** [comment]
Hi Mrs. Alynne, I've done better now.

**Linux** with **SDL2 Gamepad Tool v1.1.2**:
`03000000bd12000003c0000010010000,Joypad Alpha Shock,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,`

**Windows 10 20H2** with **SDL2 Gamepad Tool v1.2**:
`03000000bd12000003c0000000000000,Joypad Alpha Shock,platform:Windows,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`
