### ISSUE TITLE
Linux, Sony DS4 uses digital triggers when analog input is available

### ISSUE THREAD

**Issue by Alloyed** [gabomdq/SDL_GameControllerDB#47]
guid: ``030000004c050000c405000011010000``
To fix, replace:
```
lefttrigger:b6,righttrigger:b7
```
with
```
lefttrigger:a3,righttrigger:a4
```

**Comment by jck** [comment]
Why was this issue closed? The DS4 does have analog triggers.

**Comment by DavidLyhedDanielsson** [comment]
Noticed this today too and was about to post an issue when I found this. Any specific reason it was closed?

**Comment by p-groarke** [comment]
I don't know why it was closed. If you send a PR I'll accept it :)
