### ISSUE TITLE
mapping conflict between retro-bit SEGA Saturn and Retrolink SNES Controller

### ISSUE THREAD

**Issue by K4thos** [gabomdq/SDL_GameControllerDB#483]
here is mapping for SEGA Saturn® Control Pad with USB® - Black purchased here: https://retro-bit.com/sega-saturn-control-pad-with-usb-black.html
```
03000000790000001100000000000000,retro-bit SEGA Saturn Control Pad with USB,a:b1,b:b2,dpdown:+a4,dpleft:-a3,dpright:+a3,dpup:-a4,leftshoulder:b8,lefttrigger:b7,rightshoulder:b4,righttrigger:b5,start:b9,x:b0,y:b3,platform:Windows,
```
03000000790000001100000000000000 GUID is already listed on the database for Retrolink SNES Controller. The problem is that the SNES Controller has less buttons than SEGA Saturn controller, which makes the existing mapping not usable. Not sure what is the procedure in such case but I think gamepad with more buttons should have priority.

**Comment by offalynne** [comment]
Number of buttons isn’t particularly important, the more useful data point would be relative device market share, but unfortunately that data is hard to come by. There are *a lot* of SNES pads in use with this GUID. 

If I recall correctly the Saturn pad’s map is a superset of the SNES style pad so there isn’t any conflict. I’ll give this a bit more scrutiny later and replace SNES maps with the Saturn ones if that’s the case.

**Comment by offalynne** [comment]
This particular device's layout isn't an exact superset of the more common SNES pad unfortunately but it does overlap closely enough that I've authored new a map that should cover all of the buttons for both. I've authored additional maps for a few devices with similar overlap as well.
