### ISSUE TITLE
XBox One controller does not work on Raspbian using this remapping.

### ISSUE THREAD

**Issue by Fredrum** [gabomdq/SDL_GameControllerDB#497]
Hello!
I'm working on a program for Raspbian on a Raspberry Pi i4B and was hoping to use this file with SDL2 to resolve the remap needs.

But I just tested with my own controller and it does not work the mappings are still not working.
It does work if I use the SDL/test/controllermap program and the guid+remap file I get from that.

My guid was present in the SDL_GameControllerDB under 'Linux' but the remap codes were different from the ones I generated myself.

Which was a shame as I was hoping to use this repo to cover the large amount of controllers that you have here.

Any ideas of why this is happening?

Cheers
Fred

**Comment by offalynne** [comment]
Hi Fred

Please post the map you got so we can compare with what's in the DB

**Comment by Fredrum** [comment]
Hi this is the one I generated and that works with my SDL2 program,

`030000005e040000dd02000003020000,Xbox One Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,rightstick:b12,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`

I'm using SDL pulled from Github, the latest in progress from a few days ago.

**Comment by Fredrum** [comment]
Here's another controller from a user I helped with this issue,
`030000005e040000dd02000003020000,Xbox One Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,rightstick:b12,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`

You can follow our discussion here,
https://github.com/Fredrum/chiaki/issues/14

**Comment by offalynne** [comment]
The mapping comes from upstream, you'll have to take that up with the SDL project:
https://github.com/libsdl-org/SDL/blob/de6ba40d9e0dd829ab4db0567251005df1c1cbd8/src/joystick/SDL_gamecontrollerdb.h#L768

**Comment by Fredrum** [comment]
I have had a ticket there too since a few days ago but no reply at all so far.
If you know someone there maybe you would be able to get some attention?

https://github.com/libsdl-org/SDL/issues/4655

**Comment by Fredrum** [comment]
I am running without that and so is the other user.
I don't really want to add another piece of driver/software into the mix but thanks for the suggestion.

I also noticed this from June 30:
https://store.steampowered.com/news/app/312200/view/2988683441443402781

"Chasm uses SDL for low level functions like input handling, audio, etc. SDL's gamepad mapping file has entries for nearly every controller out there, so if you start the game up there's a good chance it will work right away. Problems began though when the community started adding new mappings for the PS4 controller and others that were incorrect. This caused the d-pad and other buttons to stop working or be mapped incorrectly. An update has just been released to remove the duplicate invalid mappings."

**Comment by offalynne** [comment]
The problem you quoted had to do with a specific driver problem, and it's been fixed. It shouldn't overlap with whatever you're seeing here. If you're not willing to test with the software that may help us identify the problem as asked I'm not sure how you'd like me to help you.

**Comment by Fredrum** [comment]
I just installed xboxdrv using apt on the Raspberry.
The version I get is:

Package: xboxdrv
Version: 0.8.8-1

It didn't make any difference at all to the observed behaviours.

**Comment by offalynne** [comment]
OK, thanks for clarifying Xboxdrv isn’t the issue. The next steps to resolve are: 
1. Remove the map from the db altogether locally and see if SDL handles the device fine without a mapping.
2. Install Linux on a capable PC locally, and test the your device seeing if the map is correct in that context. If it is not, check the upstream commits with git blame and contact the person who submitted it to work out the problem.
3. Investigate what driver disparities and rules differences exist between Raspbian and a full featured desktop Linux that might be responsible for the difference.
4. Continue to pursue the issue upstream (SDL’s repo, forum, and or Discord) since we largely defer to upstream, and this mapping matches the rest.

**Comment by Fredrum** [comment]
Hi thanks a lot for the helping steps!
I'ts definitely not working without the mappings either as that's how I started. I have in my notes that xbox controllers were working fine before. It has been about 6 months since I tested that. And now I'm unsure if that's correct I think it is but of course I could be wrong.
It's a bummer as I just messed up Ubunto on my dual boot PC and now I just get Kernel panic! :D  I guess this is a motivation to fix it.

If I don't install any other custom xbox drivers what is the Linux driver that handles it?

**Comment by offalynne** [comment]
I believe Xbox One controllers (depending on connectivity method) may *just work* with udev without any drivers or etc. Something weird about the GUID you reported is that the PID is 0x028e, which is clearly an *Xbox 360* device.

**Comment by Fredrum** [comment]
Iv'e spent just a little time on this in the evening and spotted that my remapping string and his remapping string (both above) have the same button and axis bindings.

`a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,rightstick:b12,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`

`a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,rightstick:b12,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,`

So I ran 'jstest' on my pad again to check and it's the same results as those above mappings.

This must mean something but I don't know what!?

**Comment by Fredrum** [comment]
I just re-flashed a microsd card with a 10 month old Raspbian OS image (official) and installed my software on that.
My Xbox One controller is working perfectly on that setup. So something has changed since then. I'm still looking for the precise change though.

These are some of the versions,

Setting up libsdl2-dev (2.0.9+dfsg1-1+rpt1) ...

-- Checking for module 'libudev'
--   Found libudev, version 241

5.4.51-v7l+

Iv'e noticed messages about the kernel driver 'xpad'. Not exactly for my symptoms though.

**Comment by Fredrum** [comment]
I believe the problem is to do with me using a Retropie image as my OS.
I couldn't reproduce the problem on official Raspberry OS image installs.

**Comment by offalynne** [comment]
Xpad is a very likely culprit. Overzealous amateur Linux driver developers often ship broken or unfinished work that takes multiple kernel releases to stabilize. Very often the eventual tweaks to make sure SDL (generally the most common use case for games on Linux derivatives) handles the device differently in a “fixed” state via the driver are not tested and thus not functional for variants like Pi and Android.

If you want to solve the problem you’re seeing at the client software level you’ll likely need a condition to explicitly target the version of Retropie it’s impacting, change the mapping accordingly, and monitor future releases in case it’s reverted.

The underlying issue will obviously mean more thorough review of the changes in Retropie.

**Comment by cgutman** [comment]
RetroPie has a custom xpad patch that switches the triggers from axes to buttons and breaks SDL gamepad mappings. I ran into this issue while testing Moonlight Embedded on RetroPie and filed https://github.com/RetroPie/RetroPie-Setup/issues/3379

**Comment by offalynne** [comment]
thanks as always @cgutman :-]

**Comment by Fredrum** [comment]
Amazing!! :D
I can confirm that once I used the Retropie packages 'dialog' gui to remove xpad my Xbox One controller worked perfectly with my software once again, no re-mapping files needed at all. Just as I remembered it.

I'm super happy to have the solution!

Thanks a lot @offalynne and @cgutman !!

Cheers!
