### ISSUE TITLE
Add mapping for controller xbox 360 rock candy

### ISSUE THREAD

**Issue by Ns816235** [gabomdq/SDL_GameControllerDB#500]
03000000c6240000fefa000000010000, xbox 360 rock candy, a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux

03000000c6240000fefa000000010000, xbox 360 rock candy, a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Windows

**Comment by offalynne** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/commit/8f1a5a2645e560e7b3b401d1e1daa3ed82dcf6b4
