### ISSUE TITLE
Benefits?

### ISSUE THREAD

**Issue by dbotha** [gabomdq/SDL_GameControllerDB#501]
Hi @gabomdq,

I stumbled upon your repo whilst adding game controller support to my SDL game. Out the box SDL appears to support the few controllers I have to hand so I'm wondering if I'm missing something - is this database a more exhaustive list? What benefits would I get from adding it to my game?

Kind regards,

Deon

**Comment by offalynne** [comment]
Diff this database against what SDL provides. Gabriel started this repo to get wider (unofficial) coverage than the SDL project itself provides. There are a lot of legacy and third-party manufactured gamepad devices out there. All of the major first-party devices are covered in SDL's db eventually. If you want more thorough coverage, use this db. The maintainers of this DB do our best to keep the data of high quality and in parity as a superset of SDL's, but unlike SDL's maintainer we do not work at Valve. If you prefer SDL's rigor and oversight, use SDL's db. Many high quality shipped titles use this DB, presumably many more do not.

**Comment by dbotha** [comment]
@offalynne Thanks for taking the time to answer the question, it's much appreciated! I understand now, I'll give this database a whirl :)
