### ISSUE TITLE
Submission for two PlayStation 2 gamepad USB adapters

### ISSUE THREAD

**Issue by dariox86** [gabomdq/SDL_GameControllerDB#502]
Missing lines for two PlayStation 2 gamepad USB adapters:

`03000000ba2200000701000001010000,Technology Innovation Engineering Ltd. TI USB Controller,platform:Linux,b:b1,a:b0,x:b3,y:b2,start:b9,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:b6,righttrigger:b7,`

and

`03000000430b00000300000000010000,EMS Production Ltd. EMS USB 2,platform:Linux,b:b1,a:b2,x:b3,y:b0,start:b9,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b6,rightshoulder:b7,dpup:b12,dpleft:b15,dpdown:b14,dpright:b13,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:b4,righttrigger:b5,`

**Comment by offalynne** [comment]
@dariox86 any chance you could generate Windows maps?

**Comment by dariox86** [comment]
These adapters are old. I don't know if they will work in Windows 11. Is it OK if I install Windows XP in a virtual machine?

**Comment by offalynne** [comment]
They should work fine in modern Windows but sure, XP is fine.

**Comment by dariox86** [comment]
Installed Windows 11 in a virtual machine and cross compiled controllermap.c. I only see a black window, maybe because hardware acceleration is not fully supported in the guest. I am having a hard time for something that is supposedly simple. Is there a suggested route for this?

**Comment by dariox86** [comment]
Unmodified lines for Technology Innovation Engineering Ltd. TI USB Controller:

`03000000ba2200000701000000000000,TI USB Controller,platform:Windows,a:b0,b:b1,x:b3,y:b2,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b6,righttrigger:b7,`

`03000000ba2200000701000001010000,Technology Innovation Engineering Ltd. TI USB Controller,platform:Linux,a:b0,b:b1,x:b3,y:b2,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b6,righttrigger:b7,`

---

Unmodified lines for EMS Production Ltd. EMS USB 2:

`03000000430b00000300000000000000,4 axis 16 button joystick,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b6,rightshoulder:b7,dpup:b12,dpdown:b14,dpleft:b15,dpright:b13,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b4,righttrigger:b5,`

`03000000430b00000300000000010000,HID 0b43:0003,platform:Linux,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b6,rightshoulder:b7,dpup:b12,dpdown:b14,dpleft:b15,dpright:b13,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b4,righttrigger:b5,`
