### ISSUE TITLE
"Joypad Storm Dazz" with wrong inputs after removal of "DragonRise Inc. Generic USB"

### ISSUE THREAD

**Issue by YeldhamDev** [gabomdq/SDL_GameControllerDB#517]
When the "DragonRise Inc. Generic USB" binding was removed in 37f3de4, this caused my "[Joypad Storm Dazz](https://images.kabum.com.br/produtos/fotos/80500/controle-dazz-storm-dualshock-xbox-360-pc-624518_1629731721_gg.jpg)" to give wrong inputs (A became X, Y became A, X became Y, and B is still B).

**Comment by offalynne** [comment]
That map fixes some devices but breaks more. See #202. If you want it mapped, use the `SDL_GAMECONTROLLERCONFIG` environment variable locally.
