### ISSUE TITLE
SideWinder Plug & Play Game Pad isn't enabled properly on linux

### ISSUE THREAD

**Issue by Erlotinib** [gabomdq/SDL_GameControllerDB#518]
Hello,

I'm the owner of a SideWinder PnP GamePad (this one https://webimg.secondhandapp.com/w-i-mgl/5a3573ab3e2617781b20954f ) which is only enabled on MacOS X.

Here is the line to enable it on linux (created with antimicrox):
`030000005e0400002700000000010000111839,Microsoft SideWinder Game Pad,a:b0,b:b1,x:b2,y:b3,lefttrigger:b4,righttrigger:b5,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftx:a0,lefty:a1,platform:Linux`

here is the result of lsusb:
045e:0027 Microsoft Corp. SideWinder PnP GamePad

thanks
julien

**Comment by offalynne** [comment]
Thank you!

**Comment by offalynne** [comment]
@Erlotinib thanks, the GUID looks a bit weird and antimicrox has proven problematic in the past; can you double check with this tool please ? https://www.generalarcade.com/gamepadtool/

**Comment by Erlotinib** [comment]
Hello,

the GUID read/generated(?) by gamepadtool is 030000005e0400002700000000010000

I tested with replacing the GUID generated by antimicrox with this one and it works flawlessly.

thanks
regard
julien

**Comment by offalynne** [comment]
thanks!
