### ISSUE TITLE
8BitDo Adapter V1 and V2 DInput maps conflict

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#533]
@8BitDo per #532 testing on V1 latest firmware as well as another user on V2, it seems that Adapter V1 and V2 have the same vendor and product ID in DInput mode but different mappings. Please let us know if this is user error or something you can/will fix with an update.

Thanks!

**Comment by mariotaku** [comment]
I have also noticed some issue with adapter v2 and asked for support by email. Hope we can have direct contact with devs of  @8BitDo. I'm happy to provide logs and do testing.

**Comment by offalynne** [comment]
The V2 has a unique PID, and mappings should not conflict. PRs forthcoming.
