### ISSUE TITLE
Wrong mapping for Xbox One Elite 2 Controller

### ISSUE THREAD

**Issue by TechGeeksIO** [gabomdq/SDL_GameControllerDB#536]
First of all, thanks for this awesome database, I had no hope that I wll get my controller running on mac and now I found this.

Unfortunately, the mapping for the Xbox One Elite 2 controller seems not to be the correct one, i tried to fix it but maybe I'm just to dumb.

My controller gets detected as "Xbox Wireless Controller", 030000005e040000220b000011050000, which already seems to be the wrong one, but if I check the mappings I found out, that the following buttons are not working:

<img width="561" alt="Screenshot 2022-01-09 at 10 38 47" src="https://user-images.githubusercontent.com/20183238/148677225-9dfb4a43-6304-4d69-bf65-9018780bdfa7.png">
<img width="563" alt="Screenshot 2022-01-09 at 10 39 10" src="https://user-images.githubusercontent.com/20183238/148677234-54d5390d-8ba1-49a6-a0fd-6dcd12763c31.png">
<img width="559" alt="Screenshot 2022-01-09 at 10 39 37" src="https://user-images.githubusercontent.com/20183238/148677237-d109afda-a722-4cb5-af77-95aaa83a8583.png">
<img width="554" alt="Screenshot 2022-01-09 at 10 40 12" src="https://user-images.githubusercontent.com/20183238/148677238-c3b64a57-360b-4d22-809b-7feceeb7db37.png">

I'm on MacOS Monterey and using the latest version of SDL2 Gamepad Tool.

I would really apprechiate any help, thanks!

**Comment by offalynne** [comment]
Axes can stick in the testing app even though the mapping is fine; you’re going to have to explain the issue in detail as those screenshots are unhelpful.

**Comment by offalynne** [comment]
@swoolcock any insight?

**Comment by TechGeeksIO** [comment]
All good, I finally got it to work, my mistake was to create a new mapping instead of using the existing one.

Thanks again, great work!
