### ISSUE TITLE
Typo in Nyko Playpad

### ISSUE THREAD

**Issue by divVerent** [gabomdq/SDL_GameControllerDB#538]
This mapping contains "rightx:a2<righty:a5".

The < should be a comma.

This currently causes parsing by glfw to fail (which in itself should probably just skip this one and proceed anyway, but that's a bug in a different project).

**Comment by offalynne** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/commit/325850b99b5846c4971d1f364183551abe1449ba
