### ISSUE TITLE
IPEGA PQ-SQ038

### ISSUE THREAD

**Issue by felagund** [gabomdq/SDL_GameControllerDB#541]
Hello,
I produced this mapping with AntiMicroX, it works for me to make the console usable with Worms W.M.D. but when I wanted to create a pull request, I noticed the produced ID is longer than the IDs in the list and then I noticed this: https://github.com/gabomdq/SDL_GameControllerDB/issues/476#issuecomment-999108966

so I am not sure it is useful, but in case it is, it is here:

```
0500000049190000020400001b01000064731026,Ipega PG-SW038,a:b0,b:b1,x:b3,y:b4,back:b10,start:b11,leftshoulder:b6,rightshoulder:b7,leftstick:b13,rightstick:b14,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,platform:Linux,
```

**Comment by offalynne** [comment]
Please refer to the tools in the ReadMe, AntiMicroX is not suitable for contributing data to the db.

**Comment by felagund** [comment]
Aha, in SDL2 Gamepad Mapper it says the mapping is

```
Mapping string for "PG-SW038" is "0500000049190000020400001b010000,Ipega PG 9069 Bluetooth Gamepad,a:b0,b:b1,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b161,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Linux,"
```

which is already in the database, but one would not expect that given my gamepad is supposed to be named PG-SW038B.

Co I guess this can be closed.

**Comment by offalynne** [comment]
Thanks for checking!
