### ISSUE TITLE
Brook PS4 + Audio PCB

### ISSUE THREAD

**Issue by hugh-braico** [gabomdq/SDL_GameControllerDB#542]
Used for fightsticks and hitboxes, so it doesn't support L3/R3 or analogue controls. 

https://www.brookaccessory.com/detail/09922855/

I used SDL2 Gamepad Tool to create this mapping:

```
03000000120c0000300e000000007801,Brook PS4+ Audio Fighting Board,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,leftshoulder:-a4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,lefttrigger:b4,righttrigger:a5,
```

**Comment by offalynne** [comment]
Thank you for the contribution. The GUID suffix suggests SDL already handles this device correctly without a need for the mapping. Have you tried it out with SDL?

**Comment by hugh-braico** [comment]
My bad! I just ctrl-F'd for my stick's guid and couldn't find it in the list, I didn't know it worked that way.

I'm testing a friend's piece of software that uses this and they suggested adding my board to the list as a solution, I guess the problem probably lies elsewhere.

**Comment by calexil** [comment]
hmm, weird.

trying to make sure the hitbox version of https://github.com/calexil/FightstickDisplay is working.

but this board is not being recognized for some reason
