### ISSUE TITLE
Mapping for MY-POWER CO.,LTD. USB 

### ISSUE THREAD

**Issue by buuf** [gabomdq/SDL_GameControllerDB#548]
030000005f1400003102000010010000
030000005f1400003102000010010000,MY-POWER CO.,LTD. USB Gamepad,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,

**Comment by offalynne** [comment]
Can you post an image or product link of the device please?

**Comment by buuf** [comment]
> Can you post an image or product link of the device please?

[https://www.amazon.com/GAMEMON-PLAYSTATION-Wired-Controller-Cable-3/dp/B07CVFJCV5](url)

**Comment by offalynne** [comment]
d42e46cee8d990c1e07194e391fdf263de0fec54
