### ISSUE TITLE
add this mapping for ps4 gamepad (destiny special edition)

### ISSUE THREAD

**Issue by TheCangroo21** [gabomdq/SDL_GameControllerDB#561]
"PS4 Controller", 030000004c050000c405000000010000 (mapping available)
Environment variable "SDL_GAMECONTROLLERCONFIG" is set to: "030000004c050000c405000000010000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,platform:Mac OS X,
"

**Comment by offalynne** [comment]
duplicate: https://github.com/gabomdq/SDL_GameControllerDB/blob/ee454a87cdac10fe0f5d56a172663e075a177c5f/gamecontrollerdb.txt#L845
