### ISSUE TITLE
Retrobit SEGA Saturn controller seems to have incorrect shoulder button mapping

### ISSUE THREAD

**Issue by Kazade** [gabomdq/SDL_GameControllerDB#562]
In the controllerdb file it's listed as having triggers and shoulder buttons - I'm not sure if there's a version that has both, but mine only has buttons. The left button seems to be mapped to left shoulder, and the right shoulder seems to be mapped to the left trigger. This mapping works properly for me (left and right shoulders map to shoulder buttons): 

```03000000790000001100000011010000,Sega Saturn,a:b1,b:b2,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b6,rightshoulder:b7,start:b9,x:b0,y:b3,platform:Linux,```

But I'm unsure if this will break something else :shrug:

**Comment by offalynne** [comment]
Please refer to the Sega mapping here: 
![](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/mapping_guide.png)

If the mapping is still wrong, feel free to update your PR.

**Comment by Kazade** [comment]
Hmm... OK so it appears it's working as intended... I have a couple of questions though...

1. What's the rationale for making the right shoulder button correspond to the left trigger, rather than the right shoulder button? 
2. I'm writing a racing game, and this mapping obviously doesn't work at all in a situation where left trigger/shoulder is brake, and right trigger/shoulder is accelerate. Is there a way to detect which mapping (sega, nintendo etc.) a controller is using?

**Comment by offalynne** [comment]
> What's the rationale for making the right shoulder button correspond to the left trigger, rather than the right shoulder button?

It is the modern standard for six button controllers:
https://www.google.com/search?q=fightpad+controller&tbm=isch

As established by fighting games:
https://www.polygon.com/street-fighter-5-guide/2017/4/24/14597504/controls

> Is there a way to detect which mapping (sega, nintendo etc.) a controller is using?

Depends on your use case, SDL offers [`SDL_GameControllerTypeForIndex`](https://wiki.libsdl.org/SDL_GameControllerTypeForIndex).

I personally maintain a [list that corresponds to mappings in this community db](https://github.com/JujuAdams/Input/blob/community-data/community_gamepad_type.txt) but have not developed a drop-in solution for use with SDL, so you'll have to handle parsing of that data yourself if you want it.
