### ISSUE TITLE
Ok to use zlib license?

### ISSUE THREAD

**Issue by blitz-research** [gabomdq/SDL_GameControllerDB#574]
Hi,

I noticed the game controller DB still uses the old SDL license. However, SDL 2.0 + itself now uses the zlib license:

https://wiki.libsdl.org/FAQLicensing

Would it be possible to change the game controller DB to to also use zlib license?

Or we world need to include 2 licenses if redistributing SDL + the game controller DB, correct?

Bye,
Mark

**Comment by offalynne** [comment]
It's the same license, just needed a format update for GH to pick it up correctly. Fixed.
