### ISSUE TITLE
Mapping for Hori Miku Project Diva X HD Controller

### ISSUE THREAD

**Issue by AndrewDWhite** [gabomdq/SDL_GameControllerDB#575]
The Hori Miku Project Diva X HD controller does not show up in the database. I have mapped both modes, ps3 and ps4, below using Steam. This is a link to what the product looked like. https://www.hlj.com/playstation-4-hatsune-miku-project-diva-x-hd-mini-controller-hrips4-061
`
030000000d0f0000a500000000000000,dev:ps4:Hori Miku Project Diva X HD,platform:Windows,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:b6,righttrigger:b7,
`
`
030000000d0f0000a600000000000000,dev:ps3:Hori Miku Project Diva X HD,platform:Windows,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,
`

**Comment by offalynne** [comment]
e24d2638657c38c4e158d18f1b4adf1092e5577c
