### ISSUE TITLE
THRUSTMASTER FireStorm Dual Power 2, mapping Inconsistent

### ISSUE THREAD

**Issue by vinceFR7528** [gabomdq/SDL_GameControllerDB#594]
Hi,
Please could you correct this gamepad mapping in your DB?
Thanks

Here is the good one I did:
030000004f04000004b3000010010000,THRUSTMASTER FireStorm Dual Power 2 - viga,a:b0,b:b2,x:b1,y:b3,back:b5,start:b7,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b6,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,platform:Linux,

**Comment by offalynne** [comment]
@vinceFR7528 will do, thanks for the mapping. does this device have 2 additional back buttons?

![](http://www.dansdata.com/images/tmsticks/fsdpunder480.jpg)

If so, can you provide the values from them via for example js-test? Thanks.

**Comment by vinceFR7528** [comment]
Here is a jstest result from the 2 additional back buttons (group of 2, left and rigth)

click on bottom left button
Event: type 1, time 14413890, number 5, value 1
Event: type 1, time 14414070, number 5, value 0

click on bottom right button
Event: type 1, time 14417290, number 7, value 1
Event: type 1, time 14417450, number 7, value 0

**Comment by offalynne** [comment]
@vinceFR7528 what “button” values are the back buttons in SDL ?

**Comment by vinceFR7528** [comment]
In your fix, you wrote the name "Thrustmaster Firestorm Dual Power" but I think the correct name is "Thrustmaster Firestorm Dual Power **2**"
Thanks

**Comment by offalynne** [comment]
Dual Power 2 and 3 appear to share the same product ID and mapping.

**Comment by vinceFR7528** [comment]
I tested under windows10 with gamepad-tool and it gives:
030000004f04000004b3000000000000,Thrustmaster Firestorm Dual Power 3,a:b0,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b5,leftx:a0,lefty:a1,rightshoulder:b6,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b1,y:b3,platform:Windows,

The id is different (identified as TFDP 3), and the 5,7 buttons are switched with the 8,9 buttons, following my first proposal.

So, to achieve the same usage with Linux or Windows, the correct final Linux mapping should be:
**SDL_GAMECONTROLLERCONFIG='030000004f04000004b3000010010000,THRUSTMASTER FireStorm Dual Power 2,a:b0,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b5,leftx:a0,lefty:a1,rightshoulder:b6,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b1,y:b3,platform:Linux,'**

Thanks
