### ISSUE TITLE
Brook PS2 to PS3/4

### ISSUE THREAD

**Issue by LodanZark** [gabomdq/SDL_GameControllerDB#602]
Would be possible to add support for the Brook PS2 to PS3/4 (old model) into db?

https://i5.walmartimages.com/asr/06891bf2-5208-4b1b-9b76-9199b385e5a0.78af82a73bd1d4095a4293f7861ff021.jpeg

`"03000000120c0000f10e000000000000,P4 Wired GamepadV2.8,platform:Windows,a:b1,b:b2,x:b0,y:b3,back:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,
"`

**Comment by offalynne** [comment]
cbd80a8dc62b8c48bce7fab7c728d7916922e507
