### ISSUE TITLE
gioteck ps3 controller not working without steam

### ISSUE THREAD

**Issue by Doctorloo56** [gabomdq/SDL_GameControllerDB#605]
i was told to copy this text here into the issue request so here

"SDL_GamepadBind"		"03000000f025000031c1000000000000,dev:gen:Gioteck PS3 Controller,platform:Windows,a:b2,b:b1,y:b0,x:b3,start:b9,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,

**Comment by offalynne** [comment]
Thank you. From where were you pointed here ?

**Comment by offalynne** [comment]
da44d1947c9e2041ebf6ce7aa12d4a95675f84c3
