### ISSUE TITLE
Mapping for PowerA Xbox One Spectra Infinity on Windows

### ISSUE THREAD

**Issue by Samutz** [gabomdq/SDL_GameControllerDB#614]
This is the same controller as the one in [PR 596](https://github.com/gabomdq/SDL_GameControllerDB/pull/596) but for Windows. Mapping was taking from Steam's config.vdf.

    030000005e040000ff02000000007801,PowerA Xbox One Spectra Infinity,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows

**Comment by offalynne** [comment]
This device should already work as intended without a map, see #478
