### ISSUE TITLE
Mayflash Wii Classic Adapter (fix)

### ISSUE THREAD

**Issue by Nyaldee** [gabomdq/SDL_GameControllerDB#624]
Hi.
The values for Windows are incorrect, the dpad and triggers do not work, those for Android are correct.

old (not work)
`0300000025090000e803000000000000,Mayflash Wii Classic Adapter,a:b1,b:b0,back:b8,dpdown:b13,dpleft:b12,dpright:b14,dpup:b11,guide:b10,leftshoulder:b4,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,platform:Windows,`

new (work)
`0300000025090000e803000000000000,Mayflash Wii Classic Adapter,a:b1,b:b0,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:a4,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:a5,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,platform:Windows,`

**Comment by offalynne** [comment]
57d4e60793a89560fd77c0524b71f9ebbef9a629
