### ISSUE TITLE
New mapping for 8BitDo Pro 2 wired in Linux

### ISSUE THREAD

**Issue by anorman728** [gabomdq/SDL_GameControllerDB#632]
I'm not 100% sure I'm doing this right (or if I should do a PR?), but here's the mapping that I just found for the 8BitDo Pro 2 wired (I'm assuming it's different from the wireless) in Linux.

`03000000c82d00001030000011010000,8BitDo 8BitDo Pro 2,platform:Linux,a:b1,b:b0,x:b4,y:b3,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,`

Tested in PCSX2 and seems to be working.

This was also created with SDL2 Gamepad Tool.  I didn't see that that was out of date until after I'd already done it.

**Comment by offalynne** [comment]
65e3231a0d46b310c0f80839d32044e6dc23040c
