### ISSUE TITLE
Mapping for 8BitDo Ultimate Bluetooth 2.4ghz

### ISSUE THREAD

**Issue by circoloco696** [gabomdq/SDL_GameControllerDB#634]
Hello, 

I created a mapping for the 8BitDo Ultimate Bluetooth controller connected on 2.4ghz for Linux.
I´m not that deep into github to add it, maybe someone can help me out.

03000000c82d00000760000011010000,8BitDo Ultimate Bluetooth 2.4ghz,a:b1,b:b0,x:b4,y:b3,back:b10,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,platform:Linux,

Greetings

**Comment by offalynne** [comment]
163e7c755cb5da3a83041756ca10457465b12950
