### ISSUE TITLE
New mapping for Rexus GX200

### ISSUE THREAD

**Issue by hersa37** [gabomdq/SDL_GameControllerDB#642]
Here's a config string for Rexus GX200. This works for the wireless mode. Changing it through GUI messes things up because the trigger buttons are also recognized as buttons first. Wired mode already works as is from what I've seen
`0300f98c632500007505000011010000,SHANWAN PS3/PC Gamepad,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,platform:Linux,crc:8cf9,
`

**Comment by offalynne** [comment]
added to https://github.com/gabomdq/SDL_GameControllerDB/pull/636 for now
