### ISSUE TITLE
Gamesir G4 Pro another mapping

### ISSUE THREAD

**Issue by koryl** [gabomdq/SDL_GameControllerDB#644]
Hi, I had problem with Gamesir G4 Pro on Linux with current mapping provided in SDL. I generated another one using Gamepad Tool and I had noticed the id for this mapping is different. I already tested it on Steam and Cemu and I think it works well. Could you add this to your controller db:

`03006877558500001b06000010010000,Gamesir_G4pro,a:b0,b:b1,x:b3,y:b4,back:b10,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,platform:Linux,`

**Comment by offalynne** [comment]
Your mapping matches ours 
https://github.com/gabomdq/SDL_GameControllerDB/blob/b71769507f36456314e1c9411526370bf82cbc02/gamecontrollerdb.txt#L1124

If your problem is with the SDL project’s mapping, take the issue upstream to SDL.
