### ISSUE TITLE
GUID for "PS3 Controller (Bluetooth)" has wrong bustype.

### ISSUE THREAD

**Issue by AlexanderKurtz** [gabomdq/SDL_GameControllerDB#66]
Hi!

The database currently contains this entry:

```
060000004c0500006802000000010000,PS3 Controller (Bluetooth),[...],platform:Linux,
```

I think that the second character (**6**) in this line is wrong, and that the correct GUID should be 0**5**0000004c0500006802000000010000. Here's why:

 - On Linux, SDL simply computes the GUID by concatenating the bustype, vendor, product and version of the input device (plus some byte-order swapping). [0]

 - After connecting my PS3 controller via Bluetooth, I get this:
   ```
   alexander@shepard:~$ grep . /sys/class/input/js0/device/id/*
   /sys/class/input/js0/device/id/bustype:0005
   /sys/class/input/js0/device/id/product:0268
   /sys/class/input/js0/device/id/vendor:054c
   /sys/class/input/js0/device/id/version:0100
   alexander@shepard:~$ 
   ```

 - The kernel header files also specify 0x05 (and not 0x06) as the bustype for Bluetooth. [1]
 - After making this one-byte change, my PS3 controller finally works ins OpenMW! ;-) [2]

Please consider making this one-byte change, so that the PS3 controller also works OOTB via Bluetooth. If there was a good reason for adding it with bustype 0x06 at the time, you might also consider keeping the old GUID and just adding a new entry!

Best regards

Alexander Kurtz

[0] https://github.com/spurious/SDL-mirror/blob/master/src/joystick/linux/SDL_sysjoystick.c#L123
[1] https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input.h#n233
[2] https://github.com/OpenMW/openmw/blob/master/files/gamecontrollerdb.txt#L96

**Comment by TiZ-EX1** [comment]
Can confirm; it should definitely be a 5 instead of a 6. Is 6 even a bus type? If so, what would it be?

**Comment by Hinsbart** [comment]
Well, on my system it's also bus type 5. But a search for "ps3 bus 006" revealed that it can indeed be 6, for some people. Maybe this was fixed in a recent driver?
So, I think it's best to keep the old mapping and just add a new one with bustype 5.

**Comment by TiZ-EX1** [comment]
I've no objections. :)

**Comment by AlexanderKurtz** [comment]
Just for the record, bus type 6 is BUS_VIRTUAL [0] and was introduced in back in 2006 [1] for (surprise!) virtual devices. I have no problem with keeping the old mapping for compatibility, but I think it shouldn't be necessary anymore on modern systems.

I have also done the search [2] mentioned by @Hinsbart, but all the results for "bus 006" seem to be from the virtual Linux root hub and not from the actual controller, so this might be a false positive.

[0] https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input.h#n234
[1] http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=9a87fdded5742a9d14780e5dfd9c940d7862e0ec
[2] https://www.google.com/search?q=ps3+bus+006

**Comment by gabomdq** [comment]
Fixed by adding duplicate entry with the alternative GUID.
