### ISSUE TITLE
Wrong mapping after upgrading firmware in Xbox Series Controller (macos)

### ISSUE THREAD

**Issue by avilches** [gabomdq/SDL_GameControllerDB#660]
Current configuration:
```030000005e040000130b000015050000,Xbox Series Controller,a:b0,b:b1,back:b10,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:a5,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,guide:b12,platform:Mac OS X,```

New configuration (using SDL2 Gamepad Tool)
```030000005e040000130b000015050000,Xbox Series Controller,a:b0,b:b1,back:b10,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:b12,dpleft:b14,dpdown:b13,dpright:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,start:b11,x:b3,y:b4,platform:Mac OS X,```

Should I upload a controller picture with serial number, or a video with the original settings and with the settings fixed?

**Comment by offalynne** [comment]
How did you update, Xbox Accessories app ?

**Comment by avilches** [comment]
Yes, it's a new controller purchased some months ago. I had problems trying to connect it to a Steam Deck and the official solution was updated it through Xbox Accessories.

**Comment by avilches** [comment]
Sorry, the name should be Xbox Series Controller too. Changed in the issue.

**Comment by offalynne** [comment]
What version of MacOS are you on ? Intel or silicon ?

**Comment by avilches** [comment]
Hi, it looks like the original mapping worked well since beginning. I guess I was using different controllers at the same time and I messed it up. I will test all controllers again, until then, I will close this issue. Thanks and apologies!
