### ISSUE TITLE
New Xbox controller mapping for MacOS

### ISSUE THREAD

**Issue by avilches** [gabomdq/SDL_GameControllerDB#661]
After upgrade the firmware in a old Xbox Wireless controller, this is the new configuration:

```030000005e040000200b000015050000,Xbox Wireless Controller,platform:Mac OS X,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,```

Should I upload a controller picture with serial number, or a video with Gamepad Tool working with this controller?

**Comment by offalynne** [comment]
2e7bc45a45c3e4dcb7eb991e893b87e46d85fc76
