### ISSUE TITLE
Add HyperKin Trooper V2 joystick for windows and Linux

### ISSUE THREAD

**Issue by skoregon** [gabomdq/SDL_GameControllerDB#670]
03000000242e00006a38000010010000,Trooper V2,platform:Linux,a:b0,b:b1,back:b4,start:b5,leftstick:-a4,leftshoulder:b2,rightshoulder:b3,leftx:a0,lefty:a1,

03000000242e00006a38000000000000,Hyperkin Trooper V2,platform:Windows,a:b0,b:b1,back:b4,start:b5,leftstick:-a4,leftshoulder:b2,rightshoulder:b3,leftx:a0,lefty:a1,

Linux and Windows mapping for the HyperKin Trooper V2 USB retro joystick. https://www.hyperkin.com/trooper-2-premium-controller-pc-mac-raspberry-pi.html

My apologies for raising an "issue".  I couldn't figure out how to edit the gamecontrollerdb.txt file itself.

**Comment by offalynne** [comment]
1566f54b177804c301b4f674ab641277086305f4
