### ISSUE TITLE
8BitDo Ultimate 2.4g DInput Bluetooth mappings 

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#673]
@8BitDo please consider adding mappings for the Ultimate 2.4g in DInput/Bluetooth mode

Thank you for considering the request.

**Comment by 8BitDo** [comment]
of course you can give me some time.

**Comment by 8BitDo** [comment]
Besides SDL2 Gamepad Tool, is there any other handy graphical generation tool? I noticed that the generated data is not the same as other content.

**Comment by offalynne** [comment]
If you're having trouble with the mapper, paste your resulting string here and we can work out the kinks together.

**Comment by offalynne** [comment]
On Linux GTK joystick tester may be useful, https://jstest-gtk.gitlab.io/

**Comment by offalynne** [comment]
> I noticed that the generated data is not the same as other content.
@8BitDo can you post the results from the mapping tool ?

**Comment by sbappudi** [comment]
Here is the mapping for this controller , if someone can create a PR and add it into the db file, that would be great!

03000000c82d00001630000011010000,8BitDo Ultimate C 2.4G Wireless Controller,a:b0,b:b1,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Linux,

**Comment by offalynne** [comment]
@sbappudi thanks for the data, just to be clear that mapping is for the C, not thr original 2.4g Ultimate with firmware update, correct ?

**Comment by offalynne** [comment]
@8BitDo 
> is there any other handy graphical generation tool

https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases

**Comment by sbappudi** [comment]
> @sbappudi thanks for the data, just to be clear that mapping is for the C, not the original 2.4g Ultimate with firmware update, correct ?

yes this mapping is for the C version of the controller

**Comment by offalynne** [comment]
> someone can create a PR

I'll author one for all platforms when I have the device in hand
