### ISSUE TITLE
Add mapping for Final Fantasy XIV game controller

### ISSUE THREAD

**Issue by Silicomancer** [gabomdq/SDL_GameControllerDB#678]
Please add the mapping for Final Fantasy XIV game controllers to your DB.

You can find images of the controller here:
https://user-images.githubusercontent.com/3684359/224511314-e715dced-d11d-47b1-9cdd-6a13da67466b.jpg
https://user-images.githubusercontent.com/3684359/224511311-4ac27d93-ce0a-4ea8-86d4-40d20e6645ee.jpg

Mapping produced with SDL2 Gamepad Mapper:
`03005036852100000201000010010000,Final Fantasy XIV,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:-a0,+leftx:+a0,-lefty:-a1,+lefty:+a1,-rightx:-a2,+rightx:+a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,`

The mapper tool asked for each button. I was not able to assign a button to the black circle in the middle of the controller image shown by the tool. I skipped it. Hope the mapping makes sense.

Are the "FUNCTION", "ANALOG" and "VIB ON/OFF" buttons of any interest for this purpose?

Is this information sufficient?

**Comment by offalynne** [comment]
Thanks ! Would love mappings for other platforms as well, if you're able. I didn't know they sold this with XIV branding -- the same device is available as a FFXI gamepad ! Always thought it looked kind of like this guy https://i.imgur.com/ajQPJDC.png 😂

> _Are the "FUNCTION", "ANALOG" and "VIB ON/OFF" buttons of any interest for this purpose?_

If you can get a mapping off `FUNCTION` it'd suit `guide` I think; no problem if not.

**Comment by offalynne** [comment]
Easy GUID port to Windows since the Linux indices match the button labels. b7e5701da82fc97beeede64d3818ef0f4d015aba

**Comment by Silicomancer** [comment]
> If you can get a mapping off `FUNCTION` it'd suit `guide` I think; no problem if not.

If I could, sure. However the mapping tool did not react to the FUNCTION button. Should it react to that button?

**Comment by Silicomancer** [comment]
> Always thought this pad kind of looks like this guy https://i.imgur.com/ajQPJDC.png joy

LOL, I can see it too :-D

**Comment by offalynne** [comment]
> the mapping tool did not react to the FUNCTION button

no problem

**Comment by drfiemost** [comment]
Even after loading the gamecontrollerdb.txt the controller is still recognized as "FUJIWORK CO., FF-GP1" and SDL_IsGameController() returns false. (https://github.com/HurricanGame/Hurrican/issues/35#issuecomment-1541528933)

The configuration string in the SDL2 internal DB is

`"03000000852100000201000000000000,FF-GP1,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b0,y:b3,",`

Any clue on what's going on?
Also noticed that SDL_GameControllerAddMappingsFromFile returns 273 lines loaded even if the file contains more than five hundred entries for Linux.
Using SDL 2.24.0

**Comment by offalynne** [comment]
Sounds like an issue for the SDL2 project.
