### ISSUE TITLE
Missing mapping for Xbox Elite Controller

### ISSUE THREAD

**Issue by isXander** [gabomdq/SDL_GameControllerDB#687]
guid 78696e70757401000000000000000000
platform windows

**Comment by isXander** [comment]
Why was this closed?

**Comment by offalynne** [comment]
Where's the mapping ?

**Comment by offalynne** [comment]
`78696e707574` -> `xinput`

https://github.com/gabomdq/SDL_GameControllerDB/blob/c5b4df0e1061175cb11e3ebbf8045178339864a5/gamecontrollerdb.txt#LL763C1-L764C1

the GUID is non-normative so I assume you're not actually using SDL to generate this ? in any case I'll accept a PR for a mapping, but 

```
guid 78696e70757401000000000000000000
platform windows
```
is not an issue, it's useless data with zero context 👍

**Comment by isXander** [comment]
Ah! God damn xinput! Sorry.
