### ISSUE TITLE
Lack of support for newer Xbox One controller

### ISSUE THREAD

**Issue by btegs** [gabomdq/SDL_GameControllerDB#69]
The newer version of the Xbox One Controller (Covert Forces, new one on shelves) doesn't seem to be supported by this .txt file. Any plans to update it with support?

**Comment by CookiePLMonster** [comment]
You can create your own mappings with Steam Big Picture mode, so I presume you could... go ahead and create it? ;)

**Comment by btegs** [comment]
You can? The controller shows up as an Xinput Controller in the controller settings and works within the interface. Are you saying there is an EXTRA step? Please provide a guide.

**Comment by CookiePLMonster** [comment]
Sounds like you're on Windows then, in this case your gamepad vendor should
not make a difference if the pad is seen as XInput.
20 kwi 2016 08:09 "btegs" <notifications@github.com> napisał(a):

**Comment by btegs** [comment]
I'm actually on Ubuntu 16.04 using a more up to date xpad driver than what is currently in the kernel: https://launchpad.net/~mdeslaur/+archive/ubuntu/steamos

**Comment by bayo** [comment]
Hi @btegs. I looks like we had the same problem. I use Ubuntu 16.04, and the mdeslaur steamos xpad kernel module. I was needed to configure SDL_GAMECONTROLLERCONFIG (http://boilingsteam.com/making-third- party-gamepads-work-with-steam-games/) to use my gamepad with Steam. I am quite sure it was not the case previously (when i was using Ubuntu 14.04 or another version of Steam or another linux kernel). But no idea what was the changes.

**Comment by cgutman** [comment]
This was fixed by 8fc65fb2056bcea5cc51c8b4a1d3cb6566de468e and can probably be closed.
