### ISSUE TITLE
8BitDo Ultimate C Wired Linux

### ISSUE THREAD

**Issue by MasterControlProgram** [gabomdq/SDL_GameControllerDB#695]
Used SDL2 Gamepad Tool which provided mapping with errors for both triggers and one dpad direction. Trigger errors were obvious fix. Figured out dpad fix using info from Issue #175. Tested successfully.

03000000c82d00001730000011010000,8BitDo Ultimate C Wired Controller,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,platform:Linux,

**Comment by offalynne** [comment]
Already in the db https://github.com/gabomdq/SDL_GameControllerDB/blob/ab9a5e8706b3bd1ad19377439d548e7554af2fef/gamecontrollerdb.txt#L1097

**Comment by MasterControlProgram** [comment]
There's already an entry with the same GUID, mappings, and platform, but a different name. Does that mean there are multiple controllers with the same GUID, or could the name be inaccurate in the existing entry?

Also, the existing entry appears to be missing the comma between name and mappings.

**Comment by offalynne** [comment]
> could the name be inaccurate in the existing entry
I've chosen the name "8BitDo Ultimate C" for all models of this device since they don't merit differentiation on connectivity method.

> the existing entry appears to be missing the comma between name and mappings
Corrected in the following commit https://github.com/gabomdq/SDL_GameControllerDB/commit/4256db51b080cade583ff888cba1f177315eaa23
