### ISSUE TITLE
Select and Start button are inverted when automapping with SDL using Dualshock2 and PS2 to PC converter

### ISSUE THREAD

**Issue by bigol83** [gabomdq/SDL_GameControllerDB#712]
I'm using a Dualshock2 official Sony controller, connected to Pcsx2 emulator with a cheap Ps2 to Pc converter. SDL automapping works mostly fine, but it has an issue while playing games: it detects SELECT button as START button and START button as SELECT

Even if the binding screen shows the buttons as they were correctly mapped, i have to manually map them to make them work as they should and they appear like this:

![ds2](https://github.com/gabomdq/SDL_GameControllerDB/assets/38129260/eb0b8288-6336-49ed-9659-9870e947fdda)

You can see the SELECT button is shown as START and viceversa, even if i pressed the correct button on my controller. 

These are my global controller settings 

![ds2_](https://github.com/gabomdq/SDL_GameControllerDB/assets/38129260/2541dd6b-f9d1-4a10-bd47-1398d0ce3a40)

I don't know if it's an issue with my converter or with the emulator mapping. My controller is definitely working as it should when connected to real Ps2.

**Comment by offalynne** [comment]
This is not the place for PCSX2 issues. Take those complaints to the PCSX2 project.

As for the mapping, review the README. We can not magically fix your issue without the hardware you have on hand. Use the gamepad tool until you have confirmed a correct mapping, and post the result if you would like the mapping corrected.

http://www.generalarcade.com/gamepadtool/
