### ISSUE TITLE
Add another Xbox One Controller

### ISSUE THREAD

**Issue by Epsilon99s** [gabomdq/SDL_GameControllerDB#717]
There are so many Xbox One Controllers out there now that some of them seem to fly under the radar and don't make it into the database. At least I couldn't find mine and thus some games and emulators don't see it. Its GUID is 030000005e040000e002000000007801

030000005e040000e002000000007801,Xbox One Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b8,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:b9,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows,

**Comment by offalynne** [comment]
> There are so many Xbox One Controllers out there now
You're telling me, sibling !!!

Thankfully SDL has an XInput driver to take care of this so we don't have to. See the `7801` suffix ("x" in ASCII) per #478

Thanks for the PR and have a great day
