### ISSUE TITLE
"DragonRise Inc. Generic USB Joystick" for linux

### ISSUE THREAD

**Issue by qurious-pixel** [gabomdq/SDL_GameControllerDB#721]
Add "DragonRise Inc. Generic USB Joystick" for linux.

```
"03002061790000000600000010010000,DragonRise Inc. Generic USB Joystick,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a3,righty:a4,start:b9,x:b3,y:b0,platform:Linux"
```

Currently a mapping does not exist for this controller.

**Comment by malmsteen06** [comment]
Add "DragonRise Inc. Generic USB Joystick" for linux.
`"03002061790000000600000010010000,DragonRise Inc. Generic USB Joystick,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a3,righty:a4,start:b9,x:b3,y:b0,platform:Linux"`
Currently a mapping does not exist for this controller.
works well in yuzu, but doesn't in cemu and ryujinx
