### ISSUE TITLE
Add DualSense Edge Controller to Windows, MacOS, and Linux 

### ISSUE THREAD

**Issue by TheBrockReal** [gabomdq/SDL_GameControllerDB#728]
The DualSense Edge has been out for a while and it should be added to the txt file

**Comment by offalynne** [comment]
This project is the product of user submission. If you want this change, buy the controller, make the mappings, and contribute them.

**Comment by TheBrockReal** [comment]
> This project is the product of user submission. If you want this change, buy the controller, make the mappings, and contribute them.

😒 I made this because I have the controller,
I have no idea how to map it
