### ISSUE TITLE
How should I setup this controller with SDL's controllermap?

### ISSUE THREAD

**Issue by leiradel** [gabomdq/SDL_GameControllerDB#77]
I want to contribute it to SDL_GameControllerDB but I'm not sure how to map it since it has less buttons than a SDL controller.

![20160604_232259](https://cloud.githubusercontent.com/assets/357536/15803272/d844242e-2aab-11e6-9786-381a90ef540d.jpg)

**Comment by leiradel** [comment]
I came up with this setup (top button line then bottom, considering SNES controller button names):

    Y X L START
    B A R SELECT

The stick is mapped as the left analog stick. That mapping yielded this string:

    c0111352000000000000504944564944,Battalife Joystick,platform:Windows,x:b4,a:b6,b:b7,y:b5,back:b2,start:b3,leftshoulder:b0,rightshoulder:b1,leftx:a0,lefty:a1,

Should I make a PR?

**Comment by gingerbeardman** [comment]
Do it :)

**Comment by gabomdq** [comment]
Added mapping manually
