### ISSUE TITLE
PS4 Controller (connected over USB cable) on my system has guide:b13 (not b12) 

### ISSUE THREAD

**Issue by gingerbeardman** [gabomdq/SDL_GameControllerDB#81]
4c05000000000000c405000000000000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b13,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,Platform:Mac OS X,

However my local config `gamecontrollerdb.local.txt` does not override `gamecontrollerdb.txt`

Any ideas?

**Comment by gabomdq** [comment]
I do not have access to a PS4 controller to verify what the right mapping is. The actual usage of the gamecontrollerdb.txt file is up to the application (SDL by default will load gamecontrollerdb.txt, but that can be overriden).

**Comment by baskerville** [comment]
The relevant entry is already in *SDL 2.04*:
```
    "4c05000000000000c405000000000000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,",
```
This is related to #102.

**Comment by Hopper262** [comment]
On the subject of the "right" mapping, it's a matter of opinion. On my PS4 controller (which admittedly has a slightly different GUID - see #113), b12 is the PlayStation logo button, which is an appropriate choice for Guide as it matches the PS3 mapping and the Xbox controller's Guide button also features a system logo.

The unmapped b13 is the clickable touchpad, which sits between Share and Options in roughly the same location as the Xbox Guide button. It's also a large and easy target to hit, so it's appealing to have it mapped.

Personally, I would have chosen to map the buttons based on my experience with native PS4 games: touchpad (b13) to Start, Options (b9) to Back, PS (b12) to Guide, with Share (b8) unmapped. That suggested mapping isn't geographically similar to an Xbox controller, but it pairs the most-frequently used actions with the most accessible buttons.

**Comment by gingerbeardman** [comment]
What was the resolution of this issue?

**Comment by p-groarke** [comment]
"The relevant entry is already in SDL 2.04:" :)
